# Dataframe loading

This notebook loads the two dataframes of purchased products and loyalty items.
For things to be weighted, aggregation must be done for better readability.

In [64]:
import pandas as pd

In [75]:
df_prod = pd.read_csv('data/20250501-carrefour_products.csv', parse_dates=['dateKey'])
df_loyalty = pd.read_csv('data/20250501-carrefour_loyalty_extended.csv', parse_dates=['date'])
# df_prod['totalPriceAfterDiscount'] = df_prod['totalPrice'] + df_prod['totalImmediateDiscount']
display(df_prod)
display(df_loyalty)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,2,0.000,2.39,4.78,-1.43,3.35,NaN
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,1,1.912,6.50,12.43,0.00,12.43,Volaille et Rôtisserie
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,1,0.000,5.39,5.39,0.00,5.39,NaN
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,1,0.000,4.99,4.99,0.00,4.99,NaN
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,1,0.000,2.45,2.45,0.00,2.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,NaN,10.0,1,0.000,1.75,1.75,0.00,1.75,NaN
5015,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,NaN,5.5,1,0.000,2.50,2.50,0.00,2.50,NaN
5016,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,NaN,5.5,1,0.000,1.99,1.99,0.00,1.99,Conserves et Bocaux
5017,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,NaN,5.5,1,0.000,0.61,0.61,0.00,0.61,NaN
5018,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,NaN,5.5,2,0.000,1.59,3.18,0.00,3.18,NaN

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[ 8.89514294e-03 2.92989891e-03 3.09790466e-...,20 OEUFS DJP POULE,0.857691,20 OEUFS DJP POULE,350G OIGN SAUCIER,0.437943,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,PCE BROCOLI FQC F,0.374859,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-1.38545979e-03 -4.68373448e-02 6.71861868e-...,1KG COUSCOUS MOYEN,0.921145,1KG COUSCOUS MOYEN,190G PESTO ROQUE-B,0.492827,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,Bananes Bio CARREFOUR BIO,0.678154,Yaourt aux fruits jaunes pêche abricot poire a...,Yaourt aux fruits jaunes pêche abricot poire a...,0.477828,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,[-5.90865640e-03 -5.82944900e-02 6.69395924e-...,CHOU FLEUR PIECE,1.000000,CHOU FLEUR PIECE,1L HUILE FLEUR DE,0.558918,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,125GX8 PAN0% JNES,0.318713,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Merging receipt details with loyalty data

In [76]:
df_loyalty_amounts = df_loyalty[['date', 'itemLabel', 'itemRd', 'matchedLabel']]

In [77]:
df_prod = pd.merge(
    df_prod,
    df_loyalty_amounts,
    how="left",
    left_on=["dateKey", "productLabel"],
    right_on=["date", "matchedLabel"],
    suffixes=("", "_loyalty"),
)

In [78]:
df_prod.query('matchedLabel.notna()')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed,date,itemLabel,itemRd,matchedLabel
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,...,0.0,5.39,5.39,0.0,5.39,NaN,2025-04-29,750G OMEGA 3 DX ST HUBERT,1.62,750G OMEGA 3 DX SH
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,NaN,5.5,...,0.0,2.59,2.59,0.0,2.59,Fruits,2025-04-25,MELON MOYEN PIECE,0.39,MELON MOYEN
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,NaN,5.5,...,0.0,2.99,2.99,0.0,2.99,Légumes,2025-04-25,MCH 500G OIGNON ROUGE FQC FR,0.45,MCH 500G OIGNON RO
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,NaN,5.5,...,0.0,3.19,3.19,0.0,3.19,Légumes,2025-04-25,FILET AIL 3 TETES,0.47,FILET AIL 3 TETES
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,NaN,5.5,...,0.0,2.49,2.49,0.0,2.49,Légumes,2025-04-25,FLT 350G ECHALOTE FQC FR,0.38,FLT 350G ECHALOTE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1618,2024-05-17,receipt,1,NaN,NaN,KIWI VERT PIECE,KIWI VERT PIECE,food,NaN,5.5,...,0.0,0.59,2.36,0.0,2.36,Fruits,2024-05-17,KIWI VERT PIECE,0.48,KIWI VERT PIECE
1624,2024-05-17,receipt,1,NaN,NaN,PCE CHOU BROCOLIS,PCE CHOU BROCOLIS,food,NaN,5.5,...,0.0,1.29,1.29,0.0,1.29,Légumes,2024-05-17,PCE CHOU BROCOLIS CRF CEE,0.25,PCE CHOU BROCOLIS
1625,2024-05-17,receipt,1,NaN,NaN,BETTERAVE FQC,BETTERAVE FQC,food,NaN,5.5,...,0.0,1.25,1.25,0.0,1.25,Légumes,2024-05-17,ST 500G BETTERAVE FQC AGR,0.25,BETTERAVE FQC
1647,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,NaN,5.5,...,0.0,0.89,0.89,0.0,0.89,NaN,2024-05-10,1KG FARINE BLE T45 CRF CLASSIC,0.13,1KG FARINE BLE T45
1648,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,NaN,5.5,...,0.0,0.89,0.89,0.0,0.89,NaN,2024-05-10,1KG FARINE BLE FLUID T45 CRF C,0.13,1KG FARINE BLE T45

In order to merge loyalty data that is not specific to one product one should also examine the category of the item.

In [63]:
df_loyalty_amounts

,date,itemLabel,itemRd,matchedLabel
0,2024-09-28,20 OEUFS DJP POULE AU SOL CRF,0.46,20 OEUFS DJP POULE
1,2024-09-28,BANANE CRF BIO MH 5 FRUITS,0.20,BANANE CRF BIO
2,2024-09-24,1KG COUSCOUS MOYEN CRF,0.30,1KG COUSCOUS MOYEN
3,2024-09-20,BANANE CRF BIO MH 5 FRUITS,0.20,Bananes Bio CARREFOUR BIO
4,2024-09-13,NaN,NaN,NaN
...,...,...,...,...
329,2025-03-08,"ART RAYON FRUITS LEG TVA 5,5",1.29,NaN
330,2025-03-08,"ART RAYON POISSONNERIE TVA 5,5",12.91,NaN
331,2025-03-08,CHOU FLEUR PIECE,0.26,CHOU FLEUR PIECE
332,2025-03-08,BANANE CRF BIO MH 5 FRUITS,0.25,BANANE CRF BIO
333,2025-03-05,NaN,NaN,NaN

In [79]:
grouped_rayon = df_loyalty_amounts.query("(itemLabel.notna()) & (itemLabel.str.contains('ART RAYON'))").groupby(['date','itemLabel']).agg(
    {
        'itemRd': 'sum',
    }
).reset_index()

In [80]:
grouped_rayon

         date                       itemLabel  itemRd
0  2024-05-17    ART RAYON FRUITS LEG TVA 5,5    0.47
1  2024-07-26    ART RAYON FRUITS LEG TVA 5,5    2.94
2  2024-08-18    ART RAYON FRUITS LEG TVA 5,5    1.02
3  2024-08-30  ART RAYON POISSONNERIE TVA 5,5    2.46
4  2024-09-11  ART RAYON POISSONNERIE TVA 5,5    9.48
5  2024-09-13    ART RAYON FRUITS LEG TVA 5,5    3.67
6  2024-10-01  ART RAYON POISSONNERIE TVA 5,5    0.88
7  2024-10-19    ART RAYON FRUITS LEG TVA 5,5    1.10
8  2024-11-19  ART RAYON POISSONNERIE TVA 5,5    2.99
9  2024-12-20    ART RAYON FRUITS LEG TVA 5,5    0.64
10 2024-12-31     ART RAYON BOUCHERIE TVA 5,5    2.90
11 2025-01-14    ART RAYON FRUITS LEG TVA 5,5    0.42
12 2025-01-21     ART RAYON BOUCHERIE TVA 5,5    2.43
13 2025-01-21    ART RAYON FRUITS LEG TVA 5,5    1.56
14 2025-01-28    ART RAYON FRUITS LEG TVA 5,5    2.17
15 2025-02-01    ART RAYON FRUITS LEG TVA 5,5    0.38
16 2025-02-06    ART RAYON FRUITS LEG TVA 5,5    0.99
17 2025-02-16    ART RAYON FRUITS LEG TVA 5,5    0.52
18 2025-02-22    ART RAYON FRUITS LEG TVA 5,5    1.11
19 2025-02-28    ART RAYON FRUITS LEG TVA 5,5    2.49
20 2025-03-08    ART RAYON FRUITS LEG TVA 5,5    1.29
21 2025-03-08  ART RAYON POISSONNERIE TVA 5,5   18.42
22 2025-03-15     ART RAYON BOUCHERIE TVA 5,5    6.60
23 2025-03-22    ART RAYON FRUITS LEG TVA 5,5    1.16
24 2025-03-29    ART RAYON FRUITS LEG TVA 5,5    3.08
25 2025-03-29  ART RAYON POISSONNERIE TVA 5,5   15.67
26 2025-04-05     ART RAYON BOUCHERIE TVA 5,5    7.77
27 2025-04-05    ART RAYON FRUITS LEG TVA 5,5    1.48
28 2025-04-12    ART RAYON FRUITS LEG TVA 5,5    3.27
29 2025-04-17    ART RAYON FRUITS LEG TVA 5,5    1.58
30 2025-04-25    ART RAYON FRUITS LEG TVA 5,5    1.36
31 2025-04-29    ART RAYON FRUITS LEG TVA 5,5    1.34

In [81]:
df_prod = pd.merge(df_prod, grouped_rayon, how='left', left_on='dateKey', right_on='date', suffixes=('', '_loyalty_rayon'))

In [82]:
df_prod.query('itemLabel_loyalty_rayon.notna()').head(30)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed,date,itemLabel,itemRd,matchedLabel,date_loyalty_rayon,itemLabel_loyalty_rayon,itemRd_loyalty_rayon
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,...,-1.43,3.35,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,...,0.00,12.43,Volaille et Rôtisserie,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,...,0.00,5.39,NaN,2025-04-29,750G OMEGA 3 DX ST HUBERT,1.62,750G OMEGA 3 DX SH,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,...,0.00,4.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,...,0.00,2.45,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,NaN,5.5,...,0.00,5.86,Légumes,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
6,2025-04-29,receipt,2,NaN,NaN,375G PIZZA BOLOGN.,375G PIZZA BOLOGN.,food,NaN,5.5,...,-1.04,4.14,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
7,2025-04-29,receipt,2,NaN,NaN,410G PIZZA 3 VIAND,410G PIZZA 3 VIAND,food,NaN,5.5,...,-1.18,4.72,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,NaN,5.5,...,0.00,1.13,Légumes,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
9,2025-04-29,receipt,1,NaN,NaN,20 OEUFS SOL,20 OEUFS SOL,food,NaN,5.5,...,0.00,5.09,Œufs,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
10,2025-04-29,receipt,2,NaN,NaN,400G COLIN FISH.CH,400G COLIN FISH.CH,food,NaN,5.5,...,-1.10,6.20,Poissons et Fruits de mer,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
11,2025-04-29,receipt,4,NaN,NaN,BT 3X110MOUCH.CONF,BT 3X110MOUCH.CONF,other,NaN,20.0,...,-2.19,12.41,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
12,2025-04-29,receipt,1,NaN,NaN,COCA-COLASSSCMINIC,COCA-COLASSSCMINIC,food,NaN,5.5,...,0.00,3.65,"Colas, Thés glacés, Sirops et Sodas",NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,NaN,5.5,...,0.00,0.69,Légumes,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
14,2025-04-29,receipt,6,NaN,NaN,OY 1KG SPAGHETTI N,OY 1KG SPAGHETTI N,food,NaN,5.5,...,0.00,11.40,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
15,2025-04-29,receipt,2,NaN,NaN,12 RLX P.HYG.3P RO,12 RLX P.HYG.3P RO,other,NaN,20.0,...,-1.38,7.80,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,NaN,5.5,...,0.00,1.24,Légumes,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
17,2025-04-29,receipt,1,NaN,NaN,132G SABLE CITRON,132G SABLE CITRON,food,NaN,5.5,...,0.00,2.49,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
18,2025-04-29,receipt,1,NaN,NaN,200G LARDONS F +30,200G LARDONS F +30,food,NaN,5.5,...,0.00,1.99,Charcuterie,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
19,2025-04-29,receipt,1,NaN,NaN,150G GATEAU FOURRE,150G GATEAU FOURRE,food,NaN,5.5,...,0.00,3.95,Gâteaux moelleux,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
20,2025-04-29,receipt,1,NaN,NaN,BARRE MINCEUR CERE,BARRE MINCEUR CERE,food,NaN,5.5,...,0.00,8.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,NaN,5.5,...,0.00,1.98,Légumes,NaT,NaN,NaN,NaN,2025-04-29,"ART RAYON FRUITS LEG TVA 5,5",1.34
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,NaN,5.5,...,0.00,2.59,Fruits,2025-04-25,MELON MOYEN PIECE,0.39,MELON MOYEN,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,NaN,5.5,...,0.00,2.99,Légumes,2025-04-25,MCH 500G OIGNON ROUGE FQC FR,0.45,MCH 500G OIGNON RO,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,NaN,5.5,...,0.00,3.19,Légumes,2025-04-25,FILET AIL 3 TETES,0.47,FILET AIL 3 TETES,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,NaN,5.5,...,0.00,2.49,Légumes,2025-04-25,FLT 350G ECHALOTE FQC FR,0.38,FLT 350G ECHALOTE,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,NaN,5.5,...,0.00,1.01,Légumes,NaT,NaN,NaN,NaN,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
27,2025-04-25,receipt,1,NaN,NaN,8X125G LAUTHENTIQ,8X125G LAUTHENTIQ,food,NaN,5.5,...,0.00,14.19,Viandes,NaT,NaN,NaN,NaN,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
28,2025-04-25,receipt,1,NaN,NaN,PAVE LE PAIN RUST,PAVE LE PAIN RUST,food,NaN,5.5,...,0.00,2.05,Pains frais,NaT,NaN,NaN,NaN,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36
29,2025-04-25,receipt,1,NaN,NaN,FLT 2KG PDT CQLP,FLT 2KG PDT CQLP,food,NaN,5.5,...,0.00,3.07,Légumes,2025-04-25,FLT 2KG PDT VP BL CQLP FR,0.46,FLT 2KG PDT CQLP,2025-04-25,"ART RAYON FRUITS LEG TVA 5,5",1.36

In [83]:
subcategories_matching = {
    "ART RAYON FRUITS LEG TVA 5,5": ["Fruits", "Légumes"],
    "ART RAYON POISSONNERIE TVA 5,5": ["Poissonnerie"],
    "ART RAYON BOUCHERIE TVA 5,5": ["Boucherie"],
    "ART RAYON CHARCUTERIE TVA 5,5": ["Charcuterie"],
}

In [84]:
df_prod["subCategory_imputed"] = df_prod["subCategory_imputed"].fillna("")
df_prod["subCategory_original"] = df_prod["subCategory_original"].fillna("")

In [85]:
# Step 1: Filter the DataFrame based on the conditions
filtered_df = df_prod[
    (df_prod["itemLabel_loyalty_rayon"].notna()) &
    (df_prod.apply(
        lambda row: any(
            row["subCategory_imputed"] in subcat 
            for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
            if row["subCategory_imputed"]
        ) | any(
            row["subCategory_original"] in subcat 
            for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
            if row["subCategory_original"]
        ),
        axis=1
    ))
]

# Step 2: Group by date and calculate the sum of "totalPriceAfterDiscount"
df_prod["totalPriceForDiscount"] = (
    filtered_df.groupby(filtered_df["dateKey"].dt.date)["totalPriceAfterDiscount"]
    .transform("sum")
)

In [86]:
df_prod.loc[df_prod.totalPriceForDiscount > 0, "amountRayonDeferred"] = (
    df_prod.loc[df_prod.totalPriceForDiscount > 0, "totalPriceAfterDiscount"]
    / df_prod.loc[df_prod.totalPriceForDiscount > 0, "totalPriceForDiscount"]
    * df_prod.loc[df_prod.totalPriceForDiscount > 0, "itemRd_loyalty_rayon"]
)

In [87]:
df_prod.fillna(
    {
        "amountRayonDeferred": 0,
        "itemRd": 0
    },
    inplace=True,
)

In [88]:
df_prod['totalTrueAmount'] = df_prod['totalPriceAfterDiscount'] - df_prod['itemRd'] - df_prod['amountRayonDeferred']
df_prod[['dateKey', 'productLabel', 'totalPriceAfterDiscount', 'itemRd', 'amountRayonDeferred', 'totalTrueAmount']].head(30)

,dateKey,productLabel,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueAmount
0,2025-04-29,5X10 D FREEDENT ME,3.35,0.00,0.000000,3.350000
1,2025-04-29,KG POULET FERMIER,12.43,0.00,0.000000,12.430000
2,2025-04-29,750G OMEGA 3 DX SH,5.39,1.62,0.000000,3.770000
3,2025-04-29,3 RECH RUBAN MAGI,4.99,0.00,0.000000,4.990000
4,2025-04-29,132G BISC.COCO SSA,2.45,0.00,0.000000,2.450000
5,2025-04-29,KG TOMATE GRAP FR,5.86,0.00,0.720404,5.139596
6,2025-04-29,375G PIZZA BOLOGN.,4.14,0.00,0.000000,4.140000
7,2025-04-29,410G PIZZA 3 VIAND,4.72,0.00,0.000000,4.720000
8,2025-04-29,AUBERGINE VRAC,1.13,0.00,0.138917,0.991083
9,2025-04-29,20 OEUFS SOL,5.09,0.00,0.000000,5.090000
10,2025-04-29,400G COLIN FISH.CH,6.20,0.00,0.000000,6.200000
11,2025-04-29,BT 3X110MOUCH.CONF,12.41,0.00,0.000000,12.410000
12,2025-04-29,COCA-COLASSSCMINIC,3.65,0.00,0.000000,3.650000
13,2025-04-29,POIVRON ROUGE,0.69,0.00,0.084826,0.605174
14,2025-04-29,OY 1KG SPAGHETTI N,11.40,0.00,0.000000,11.400000
15,2025-04-29,12 RLX P.HYG.3P RO,7.80,0.00,0.000000,7.800000
16,2025-04-29,HARICOT VERT FIN,1.24,0.00,0.152440,1.087560
17,2025-04-29,132G SABLE CITRON,2.49,0.00,0.000000,2.490000
18,2025-04-29,200G LARDONS F +30,1.99,0.00,0.000000,1.990000
19,2025-04-29,150G GATEAU FOURRE,3.95,0.00,0.000000,3.950000
20,2025-04-29,BARRE MINCEUR CERE,8.99,0.00,0.000000,8.990000
21,2025-04-29,BQ TOM CERISE ALL,1.98,0.00,0.243413,1.736587
22,2025-04-25,MELON MOYEN,2.59,0.39,0.081386,2.118614
23,2025-04-25,MCH 500G OIGNON RO,2.99,0.45,0.093956,2.446044
24,2025-04-25,FILET AIL 3 TETES,3.19,0.47,0.100240,2.619760
25,2025-04-25,FLT 350G ECHALOTE,2.49,0.38,0.078244,2.031756
26,2025-04-25,COURGETTE,1.01,0.00,0.031738,0.978262
27,2025-04-25,8X125G LAUTHENTIQ,14.19,0.00,0.000000,14.190000
28,2025-04-25,PAVE LE PAIN RUST,2.05,0.00,0.000000,2.050000
29,2025-04-25,FLT 2KG PDT CQLP,3.07,0.46,0.096470,2.513530

In [90]:
df_prod.loc[df_prod.totalWeight > 0, "totalTrueUnitPrice"] = (
    df_prod.loc[df_prod.totalWeight > 0, "totalTrueAmount"]
    / df_prod.loc[df_prod.totalWeight > 0, "totalWeight"]
)

In [91]:
df_prod.query('productLabel.str.contains("saumon", case=False)')[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

,dateKey,productLabel,unitPrice,totalWeight,totalPrice,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueUnitPrice,totalTrueAmount
227,2025-03-29,FILET SAUMON FQC A,18.99,3.300,62.66,62.66,0.0,0.000000,18.987879,62.660000
228,2025-03-29,FILET SAUMON FQC A,18.99,3.300,62.66,62.66,0.0,9.243854,16.186711,53.416146
307,2025-03-08,PAVE SAUMON,19.99,1.854,37.06,36.76,0.0,0.000000,19.827400,36.760000
308,2025-03-08,PAVE SAUMON,19.99,1.854,37.06,36.76,0.0,8.021789,15.500653,28.738211
669,2024-12-27,SAUMON ENTIER,8.90,2.913,25.93,25.93,0.0,0.000000,8.901476,25.930000
737,2024-12-15,420G PIZZA SAUMON,2.25,0.000,4.50,3.82,0.0,0.000000,NaN,3.820000
827,2024-11-19,TARTE SAUMON POIR.,3.89,0.000,7.78,5.45,0.0,0.000000,NaN,5.450000
840,2024-11-19,SAUMON ENTIER,9.99,1.998,19.96,19.96,0.0,2.256348,8.860687,17.703652
1134,2024-09-11,FILET SAUMON FQC A,11.99,5.268,63.17,63.17,0.0,6.508549,10.755780,56.661451
1979,2024-03-23,SAUMON ENTIER,11.99,4.904,58.80,58.80,0.0,0.000000,11.990212,58.800000
2667,2023-11-24,SAUMON ENTIER,9.99,2.808,28.05,28.05,0.0,0.000000,9.989316,28.050000
2945,2023-09-19,SAUMON ENTIER,9.99,2.430,24.28,24.28,0.0,0.000000,9.991770,24.280000
2986,2023-09-15,FILET SAUMON FQC A,12.99,2.218,28.81,28.81,0.0,0.000000,12.989179,28.810000
3167,2023-08-11,SAUMON ENTIER,9.99,5.700,56.94,56.94,0.0,0.000000,9.989474,56.940000
3181,2023-08-04,FILET SAUMON FQC A,13.99,2.310,32.32,32.32,0.0,0.000000,13.991342,32.320000
4098,2022-12-31,PAVE SAUMON,15.00,0.000,15.00,15.00,0.0,0.000000,NaN,15.000000
4870,2022-06-29,SAUMON SCE OSEILLE,4.95,0.000,4.95,4.95,0.0,0.000000,NaN,4.950000

In [60]:
df_loyalty

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[ 8.89514294e-03 2.92989891e-03 3.09790466e-...,20 OEUFS DJP POULE,0.857691,20 OEUFS DJP POULE,350G OIGN SAUCIER,0.437943,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,PCE BROCOLI FQC F,0.374859,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-1.38545979e-03 -4.68373448e-02 6.71861868e-...,1KG COUSCOUS MOYEN,0.921145,1KG COUSCOUS MOYEN,190G PESTO ROQUE-B,0.492827,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,Bananes Bio CARREFOUR BIO,0.678154,Yaourt aux fruits jaunes pêche abricot poire a...,Yaourt aux fruits jaunes pêche abricot poire a...,0.477828,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,[-5.90865640e-03 -5.82944900e-02 6.69395924e-...,CHOU FLEUR PIECE,1.000000,CHOU FLEUR PIECE,1L HUILE FLEUR DE,0.558918,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,125GX8 PAN0% JNES,0.318713,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN