# Dataframe loading

This notebook loads the two dataframes of purchased products and loyalty items.
For things to be weighted, aggregation must be done for better readability.

In [ ]:
import sys
sys.path.append("..")

In [1]:
import pandas as pd

In [ ]:
df_prod = pd.read_csv('../data/20250501-carrefour_products.csv', parse_dates=['dateKey'])
df_loyalty = pd.read_csv('../data/20250501-carrefour_loyalty_extended.csv', parse_dates=['date'])
df_prod['totalPriceAfterDiscount'] = df_prod['totalPrice'] + df_prod['totalImmediateDiscount']
display(df_prod)
display(df_loyalty)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,2,0.000,2.39,4.78,-1.43,3.35,NaN
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,1,1.912,6.50,12.43,0.00,12.43,Volaille et Rôtisserie
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,1,0.000,5.39,5.39,0.00,5.39,NaN
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,1,0.000,4.99,4.99,0.00,4.99,NaN
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,1,0.000,2.45,2.45,0.00,2.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,NaN,10.0,1,0.000,1.75,1.75,0.00,1.75,NaN
5015,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,NaN,5.5,1,0.000,2.50,2.50,0.00,2.50,NaN
5016,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,NaN,5.5,1,0.000,1.99,1.99,0.00,1.99,Conserves et Bocaux
5017,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,NaN,5.5,1,0.000,0.61,0.61,0.00,0.61,NaN
5018,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,NaN,5.5,2,0.000,1.59,3.18,0.00,3.18,NaN

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[ 8.89514294e-03 2.92989891e-03 3.09790466e-...,20 OEUFS DJP POULE,0.857691,20 OEUFS DJP POULE,350G OIGN SAUCIER,0.437943,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,PCE BROCOLI FQC F,0.374859,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-1.38545979e-03 -4.68373448e-02 6.71861868e-...,1KG COUSCOUS MOYEN,0.921145,1KG COUSCOUS MOYEN,190G PESTO ROQUE-B,0.492827,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,Bananes Bio CARREFOUR BIO,0.678154,Yaourt aux fruits jaunes pêche abricot poire a...,Yaourt aux fruits jaunes pêche abricot poire a...,0.477828,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,[-5.90865640e-03 -5.82944900e-02 6.69395924e-...,CHOU FLEUR PIECE,1.000000,CHOU FLEUR PIECE,1L HUILE FLEUR DE,0.558918,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,[-8.01151327e-04 1.81768388e-02 3.72067164e-...,BANANE CRF BIO,0.745447,BANANE CRF BIO,125GX8 PAN0% JNES,0.318713,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Merging receipt details with loyalty data

In [3]:
df_loyalty_amounts = df_loyalty[['date', 'itemLabel', 'itemRd', 'matchedLabel']]

In [21]:
df_loyalty_amounts

,date,itemLabel,itemRd,matchedLabel
0,2024-09-28,20 OEUFS DJP POULE AU SOL CRF,0.46,20 OEUFS DJP POULE
1,2024-09-28,BANANE CRF BIO MH 5 FRUITS,0.20,BANANE CRF BIO
2,2024-09-24,1KG COUSCOUS MOYEN CRF,0.30,1KG COUSCOUS MOYEN
3,2024-09-20,BANANE CRF BIO MH 5 FRUITS,0.20,Bananes Bio CARREFOUR BIO
4,2024-09-13,NaN,NaN,NaN
...,...,...,...,...
329,2025-03-08,"ART RAYON FRUITS LEG TVA 5,5",1.29,NaN
330,2025-03-08,"ART RAYON POISSONNERIE TVA 5,5",12.91,NaN
331,2025-03-08,CHOU FLEUR PIECE,0.26,CHOU FLEUR PIECE
332,2025-03-08,BANANE CRF BIO MH 5 FRUITS,0.25,BANANE CRF BIO
333,2025-03-05,NaN,NaN,NaN

In [25]:
df_prod = pd.merge(
    df_prod,
    df_loyalty_amounts,
    how="left",
    left_on=["dateKey", "productLabel"],
    right_on=["date", "matchedLabel"],
    suffixes=("", "_loyalty"),
)

In [26]:
df_prod.query('productLabel.str.contains("SAUMON", case=False)')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed,date,itemLabel,itemRd,matchedLabel
189,2025-03-29,receipt,2,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,3.300,18.99,62.66,0.00,62.66,Poissonnerie,NaT,NaN,NaN,NaN
249,2025-03-08,receipt,2,NaN,NaN,PAVE SAUMON,PAVE SAUMON,food,NaN,5.5,...,1.854,19.99,37.06,-0.30,36.76,Poissonnerie,NaT,NaN,NaN,NaN
557,2024-12-27,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.913,8.90,25.93,0.00,25.93,Poissonnerie,NaT,NaN,NaN,NaN
625,2024-12-15,receipt,2,NaN,NaN,420G PIZZA SAUMON,420G PIZZA SAUMON,food,NaN,5.5,...,0.000,2.25,4.50,-0.68,3.82,NaN,NaT,NaN,NaN,NaN
715,2024-11-19,receipt,2,NaN,NaN,TARTE SAUMON POIR.,TARTE SAUMON POIR.,food,NaN,5.5,...,0.000,3.89,7.78,-2.33,5.45,NaN,NaT,NaN,NaN,NaN
728,2024-11-19,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,1.998,9.99,19.96,0.00,19.96,Poissonnerie,NaT,NaN,NaN,NaN
1022,2024-09-11,receipt,2,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,5.268,11.99,63.17,0.00,63.17,Poissonnerie,NaT,NaN,NaN,NaN
1867,2024-03-23,receipt,2,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,4.904,11.99,58.80,0.00,58.80,Poissonnerie,NaT,NaN,NaN,NaN
2555,2023-11-24,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.808,9.99,28.05,0.00,28.05,Poissonnerie,NaT,NaN,NaN,NaN
2833,2023-09-19,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.430,9.99,24.28,0.00,24.28,Poissonnerie,NaT,NaN,NaN,NaN
2874,2023-09-15,receipt,1,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,2.218,12.99,28.81,0.00,28.81,Poissonnerie,NaT,NaN,NaN,NaN
3055,2023-08-11,receipt,2,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,5.700,9.99,56.94,0.00,56.94,Poissonnerie,NaT,NaN,NaN,NaN
3069,2023-08-04,receipt,1,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,2.310,13.99,32.32,0.00,32.32,Poissonnerie,NaT,NaN,NaN,NaN
3986,2022-12-31,receipt,1,NaN,NaN,PAVE SAUMON,PAVE SAUMON,food,NaN,5.5,...,0.000,15.00,15.00,0.00,15.00,Poissonnerie,NaT,NaN,NaN,NaN
4758,2022-06-29,receipt,1,NaN,NaN,SAUMON SCE OSEILLE,SAUMON SCE OSEILLE,food,NaN,5.5,...,0.000,4.95,4.95,0.00,4.95,NaN,NaT,NaN,NaN,NaN

In order to merge loyalty data that is not specific to one product one should also examine the category of the item.

In [27]:
grouped_rayon = df_loyalty_amounts.query("(itemLabel.notna()) & (itemLabel.str.contains('ART RAYON'))").groupby(['date','itemLabel']).agg(
    {
        'itemRd': 'sum',
    }
).reset_index()

In [28]:
grouped_rayon

         date                       itemLabel  itemRd
0  2024-05-17    ART RAYON FRUITS LEG TVA 5,5    0.47
1  2024-07-26    ART RAYON FRUITS LEG TVA 5,5    2.94
2  2024-08-18    ART RAYON FRUITS LEG TVA 5,5    1.02
3  2024-08-30  ART RAYON POISSONNERIE TVA 5,5    2.46
4  2024-09-11  ART RAYON POISSONNERIE TVA 5,5    9.48
5  2024-09-13    ART RAYON FRUITS LEG TVA 5,5    3.67
6  2024-10-01  ART RAYON POISSONNERIE TVA 5,5    0.88
7  2024-10-19    ART RAYON FRUITS LEG TVA 5,5    1.10
8  2024-11-19  ART RAYON POISSONNERIE TVA 5,5    2.99
9  2024-12-20    ART RAYON FRUITS LEG TVA 5,5    0.64
10 2024-12-31     ART RAYON BOUCHERIE TVA 5,5    2.90
11 2025-01-14    ART RAYON FRUITS LEG TVA 5,5    0.42
12 2025-01-21     ART RAYON BOUCHERIE TVA 5,5    2.43
13 2025-01-21    ART RAYON FRUITS LEG TVA 5,5    1.56
14 2025-01-28    ART RAYON FRUITS LEG TVA 5,5    2.17
15 2025-02-01    ART RAYON FRUITS LEG TVA 5,5    0.38
16 2025-02-06    ART RAYON FRUITS LEG TVA 5,5    0.99
17 2025-02-16    ART RAYON FRUITS LEG TVA 5,5    0.52
18 2025-02-22    ART RAYON FRUITS LEG TVA 5,5    1.11
19 2025-02-28    ART RAYON FRUITS LEG TVA 5,5    2.49
20 2025-03-08    ART RAYON FRUITS LEG TVA 5,5    1.29
21 2025-03-08  ART RAYON POISSONNERIE TVA 5,5   18.42
22 2025-03-15     ART RAYON BOUCHERIE TVA 5,5    6.60
23 2025-03-22    ART RAYON FRUITS LEG TVA 5,5    1.16
24 2025-03-29    ART RAYON FRUITS LEG TVA 5,5    3.08
25 2025-03-29  ART RAYON POISSONNERIE TVA 5,5   15.67
26 2025-04-05     ART RAYON BOUCHERIE TVA 5,5    7.77
27 2025-04-05    ART RAYON FRUITS LEG TVA 5,5    1.48
28 2025-04-12    ART RAYON FRUITS LEG TVA 5,5    3.27
29 2025-04-17    ART RAYON FRUITS LEG TVA 5,5    1.58
30 2025-04-25    ART RAYON FRUITS LEG TVA 5,5    1.36
31 2025-04-29    ART RAYON FRUITS LEG TVA 5,5    1.34

In [29]:
groupedByDate_rayon = pd.pivot_table(
    grouped_rayon,
    index="date",
    columns="itemLabel",
    values="itemRd",
    aggfunc="sum",
    fill_value=0,
).reset_index()

In [8]:
groupedByDate_rayon

itemLabel,date,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5"
0,2024-05-17,0.00,0.47,0.00
1,2024-07-26,0.00,2.94,0.00
2,2024-08-18,0.00,1.02,0.00
3,2024-08-30,0.00,0.00,2.46
4,2024-09-11,0.00,0.00,9.48
5,2024-09-13,0.00,3.67,0.00
6,2024-10-01,0.00,0.00,0.88
7,2024-10-19,0.00,1.10,0.00
8,2024-11-19,0.00,0.00,2.99
9,2024-12-20,0.00,0.64,0.00
10,2024-12-31,2.90,0.00,0.00
11,2025-01-14,0.00,0.42,0.00
12,2025-01-21,2.43,1.56,0.00
13,2025-01-28,0.00,2.17,0.00
14,2025-02-01,0.00,0.38,0.00
15,2025-02-06,0.00,0.99,0.00
16,2025-02-16,0.00,0.52,0.00
17,2025-02-22,0.00,1.11,0.00
18,2025-02-28,0.00,2.49,0.00
19,2025-03-08,0.00,1.29,18.42
20,2025-03-15,6.60,0.00,0.00
21,2025-03-22,0.00,1.16,0.00
22,2025-03-29,0.00,3.08,15.67
23,2025-04-05,7.77,1.48,0.00
24,2025-04-12,0.00,3.27,0.00
25,2025-04-17,0.00,1.58,0.00
26,2025-04-25,0.00,1.36,0.00
27,2025-04-29,0.00,1.34,0.00

In [30]:
df_prod = pd.merge(df_prod, groupedByDate_rayon, how='left', left_on='dateKey', right_on='date', suffixes=('', '_loyalty_rayon'))

In [10]:
df_prod.head(30)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,totalPriceAfterDiscount,subCategory_imputed,date,itemLabel,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5"
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,...,3.35,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,...,12.43,Volaille et Rôtisserie,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,...,5.39,NaN,2025-04-29,750G OMEGA 3 DX ST HUBERT,1.62,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,...,4.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,...,2.45,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,NaN,5.5,...,5.86,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
6,2025-04-29,receipt,2,NaN,NaN,375G PIZZA BOLOGN.,375G PIZZA BOLOGN.,food,NaN,5.5,...,4.14,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
7,2025-04-29,receipt,2,NaN,NaN,410G PIZZA 3 VIAND,410G PIZZA 3 VIAND,food,NaN,5.5,...,4.72,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,NaN,5.5,...,1.13,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
9,2025-04-29,receipt,1,NaN,NaN,20 OEUFS SOL,20 OEUFS SOL,food,NaN,5.5,...,5.09,Œufs,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
10,2025-04-29,receipt,2,NaN,NaN,400G COLIN FISH.CH,400G COLIN FISH.CH,food,NaN,5.5,...,6.20,Poissons et Fruits de mer,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
11,2025-04-29,receipt,4,NaN,NaN,BT 3X110MOUCH.CONF,BT 3X110MOUCH.CONF,other,NaN,20.0,...,12.41,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
12,2025-04-29,receipt,1,NaN,NaN,COCA-COLASSSCMINIC,COCA-COLASSSCMINIC,food,NaN,5.5,...,3.65,"Colas, Thés glacés, Sirops et Sodas",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,NaN,5.5,...,0.69,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
14,2025-04-29,receipt,6,NaN,NaN,OY 1KG SPAGHETTI N,OY 1KG SPAGHETTI N,food,NaN,5.5,...,11.40,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
15,2025-04-29,receipt,2,NaN,NaN,12 RLX P.HYG.3P RO,12 RLX P.HYG.3P RO,other,NaN,20.0,...,7.80,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,NaN,5.5,...,1.24,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
17,2025-04-29,receipt,1,NaN,NaN,132G SABLE CITRON,132G SABLE CITRON,food,NaN,5.5,...,2.49,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
18,2025-04-29,receipt,1,NaN,NaN,200G LARDONS F +30,200G LARDONS F +30,food,NaN,5.5,...,1.99,Charcuterie,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
19,2025-04-29,receipt,1,NaN,NaN,150G GATEAU FOURRE,150G GATEAU FOURRE,food,NaN,5.5,...,3.95,Gâteaux moelleux,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
20,2025-04-29,receipt,1,NaN,NaN,BARRE MINCEUR CERE,BARRE MINCEUR CERE,food,NaN,5.5,...,8.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,NaN,5.5,...,1.98,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,NaN,5.5,...,2.59,Fruits,2025-04-25,MELON MOYEN PIECE,0.39,MELON MOYEN,2025-04-25,0.0,1.36,0.0
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,NaN,5.5,...,2.99,Légumes,2025-04-25,MCH 500G OIGNON ROUGE FQC FR,0.45,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,NaN,5.5,...,3.19,Légumes,2025-04-25,FILET AIL 3 TETES,0.47,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,NaN,5.5,...,2.49,Légumes,2025-04-25,FLT 350G ECHALOTE FQC FR,0.38,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,NaN,5.5,...,1.01,Légumes,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
27,2025-04-25,receipt,1,NaN,NaN,8X125G LAUTHENTIQ,8X125G LAUTHENTIQ,food,NaN,5.5,...,14.19,Viandes,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
28,2025-04-25,receipt,1,NaN,NaN,PAVE LE PAIN RUST,PAVE LE PAIN RUST,food,NaN,5.5,...,2.05,Pains frais,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
29,2025-04-25,receipt,1,NaN,NaN,FLT 2KG PDT CQLP,FLT 2KG PDT CQLP,food,NaN,5.5,...,3.07,Légumes,2025-04-25,FLT 2KG PDT VP BL CQLP FR,0.46,FLT 2KG PDT CQLP,2025-04-25,0.0,1.36,0.0

In [31]:
subcategories_matching = {
    "ART RAYON FRUITS LEG TVA 5,5": ["Fruits", "Légumes"],
    "ART RAYON POISSONNERIE TVA 5,5": ["Poissonnerie"],
    "ART RAYON BOUCHERIE TVA 5,5": ["Boucherie"],
    "ART RAYON CHARCUTERIE TVA 5,5": ["Charcuterie"],
}

In [32]:
df_prod["subCategory_imputed"] = df_prod["subCategory_imputed"].fillna("")
df_prod["subCategory_original"] = df_prod["subCategory_original"].fillna("")
df_prod["itemRd"] = df_prod["itemRd"].fillna(0)

In [33]:
# Step 1: Filter the DataFrame based on the conditions
# filtered_df = df_prod[
#     (df_prod["itemLabel_loyalty_rayon"].notna()) &
#     (df_prod.apply(
#         lambda row: any(
#             row["subCategory_imputed"] in subcat 
#             for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
#             if row["subCategory_imputed"]
#         ) | any(
#             row["subCategory_original"] in subcat 
#             for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
#             if row["subCategory_original"]
#         ),
#         axis=1
#     ))
# ]

# Step 2: Group by date and calculate the sum of "totalPriceAfterDiscount"
for subitem, categories in subcategories_matching.items():
    # Step 1: Filter the DataFrame based on the conditions
    filtered_df = df_prod[
        (df_prod.apply(
            lambda row: any(
                row["subCategory_imputed"] in subcat 
                for subcat in categories
                if row["subCategory_imputed"]
            ) | any(
                row["subCategory_original"] in subcat 
                for subcat in categories
                if row["subCategory_original"]
            ),
            axis=1)
        ) &
        (df_prod["itemRd"] == 0)
    ]
    df_prod[f"totalPrice_{subitem}"] = (
        filtered_df.groupby(filtered_df["dateKey"].dt.date)["totalPriceAfterDiscount"]
    ).transform("sum")

In [15]:
df_prod[df_prod["totalPrice_ART RAYON FRUITS LEG TVA 5,5"].notna()].head(30)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5"
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
34,2025-04-25,receipt,1,NaN,NaN,POIVRON JAUNE,POIVRON JAUNE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
37,2025-04-25,receipt,1,NaN,NaN,POMME GRANNY GROSS,POMME GRANNY GROSS,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
41,2025-04-25,receipt,1,NaN,NaN,MENTHE,MENTHE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
46,2025-04-25,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
48,2025-04-25,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
57,2025-04-17,receipt,1,NaN,NaN,PATATE DOUCE VRAC,PATATE DOUCE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
58,2025-04-17,receipt,1,NaN,NaN,POMME TERRE STD,POMME TERRE STD,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
60,2025-04-17,receipt,2,NaN,NaN,250GR NOIX FRANC,250GR NOIX FRANC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
76,2025-04-17,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
78,2025-04-17,receipt,1,NaN,NaN,PIMENT VERT,PIMENT VERT,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
97,2025-04-17,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
99,2025-04-17,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
106,2025-04-12,receipt,1,NaN,NaN,CELERI BRANCHE,CELERI BRANCHE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
108,2025-04-12,receipt,1,NaN,NaN,POMME GOLDEN FQC,POMME GOLDEN FQC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
111,2025-04-12,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
114,2025-04-12,receipt,1,NaN,NaN,COURGETTE RONDE,COURGETTE RONDE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
117,2025-04-12,receipt,1,NaN,NaN,ST EPINARD A CUIRE,ST EPINARD A CUIRE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
119,2025-04-12,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
122,2025-04-12,receipt,1,NaN,NaN,POMME TERRE STD,POMME TERRE STD,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
123,2025-04-12,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
125,2025-04-12,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
126,2025-04-12,receipt,1,NaN,NaN,POIREAU VRAC,POIREAU VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
127,2025-04-12,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
128,2025-04-12,receipt,1,NaN,NaN,BROCOLI VRAC,BROCOLI VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN

In [46]:
df_prod.query('itemRd.notna()')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5"
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,1.62,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,,5.5,...,0.39,MELON MOYEN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,,5.5,...,0.45,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,,5.5,...,0.47,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,,5.5,...,0.38,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1618,2024-05-17,receipt,1,NaN,NaN,KIWI VERT PIECE,KIWI VERT PIECE,food,,5.5,...,0.48,KIWI VERT PIECE,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1624,2024-05-17,receipt,1,NaN,NaN,PCE CHOU BROCOLIS,PCE CHOU BROCOLIS,food,,5.5,...,0.25,PCE CHOU BROCOLIS,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1625,2024-05-17,receipt,1,NaN,NaN,BETTERAVE FQC,BETTERAVE FQC,food,,5.5,...,0.25,BETTERAVE FQC,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1647,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,,5.5,...,0.13,1KG FARINE BLE T45,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1648,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,,5.5,...,0.13,1KG FARINE BLE T45,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df_prod.query("dateKey == @pd.to_datetime('2025-04-25')")[["dateKey", "productLabel", "subCategory_imputed", "totalPriceAfterDiscount", "itemRd", "ART RAYON FRUITS LEG TVA 5,5", "totalPrice_ART RAYON FRUITS LEG TVA 5,5"]].head(30)

,dateKey,productLabel,subCategory_imputed,totalPriceAfterDiscount,itemRd,"ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5"
22,2025-04-25,MELON MOYEN,Fruits,2.59,0.39,1.36,NaN
23,2025-04-25,MCH 500G OIGNON RO,Légumes,2.99,0.45,1.36,NaN
24,2025-04-25,FILET AIL 3 TETES,Légumes,3.19,0.47,1.36,NaN
25,2025-04-25,FLT 350G ECHALOTE,Légumes,2.49,0.38,1.36,NaN
26,2025-04-25,COURGETTE,Légumes,1.01,0.00,1.36,9.38
27,2025-04-25,8X125G LAUTHENTIQ,Viandes,14.19,0.00,1.36,NaN
28,2025-04-25,PAVE LE PAIN RUST,Pains frais,2.05,0.00,1.36,NaN
29,2025-04-25,FLT 2KG PDT CQLP,Légumes,3.07,0.46,1.36,NaN
30,2025-04-25,16X125 NATUR DANON,Yaourts et Fromages blancs,3.35,0.00,1.36,NaN
31,2025-04-25,320G JB SP DD SSOG,,4.75,0.00,1.36,NaN
32,2025-04-25,CELERI BRANCHE,Légumes,0.72,0.14,1.36,NaN
33,2025-04-25,BANANE CRF BIO,Fruits,1.99,0.30,1.36,NaN
34,2025-04-25,POIVRON JAUNE,Légumes,2.23,0.00,1.36,9.38
35,2025-04-25,850G SKYR NATURE Y,Yaourts et Fromages blancs,3.39,0.00,1.36,NaN
36,2025-04-25,125GX16 PAN0% PAN,Yaourts et Fromages blancs,4.59,0.00,1.36,NaN
37,2025-04-25,POMME GRANNY GROSS,Fruits,2.64,0.00,1.36,9.38
38,2025-04-25,BRANDADE MORUE,Poissonnerie,8.89,0.00,1.36,NaN
39,2025-04-25,BATAVIA PIECE,Légumes,1.29,0.20,1.36,NaN
40,2025-04-25,AVOCAT PIECE,Légumes,2.78,0.41,1.36,NaN
41,2025-04-25,MENTHE,Légumes,0.99,0.00,1.36,9.38
42,2025-04-25,ORANGE DESSERT 2KG,Fruits,3.49,0.52,1.36,NaN
43,2025-04-25,PAIN CHOC PB X5 +,,4.99,0.00,1.36,NaN
44,2025-04-25,KIWI VERT PIECE,Fruits,5.52,0.83,1.36,NaN
45,2025-04-25,CHOU FLEUR PIECE,Légumes,2.49,0.38,1.36,NaN
46,2025-04-25,POIRE CONFERENCE,Fruits,1.63,0.00,1.36,9.38
47,2025-04-25,CONCOMBRE PIECE,Légumes,1.29,0.20,1.36,NaN
48,2025-04-25,CAROTTE VRAC,Légumes,0.88,0.00,1.36,9.38
49,2025-04-25,1L HUILE FLEUR DE,"Huiles, Vinaigres et Vinaigrettes",2.95,0.00,1.36,NaN

In [24]:
df_prod.columns

Index(['dateKey', 'recordType', 'countVisits', 'ean', 'cdbase', 'productLabel',
       'slugProductLabel', 'category', 'subCategory_original', 'vatPercentage',
       'totalQuantity', 'totalWeight', 'unitPrice', 'totalPrice',
       'totalImmediateDiscount', 'totalPriceAfterDiscount',
       'subCategory_imputed'],
      dtype='object')

In [34]:
# Define the mask for filtering rows
mask = (
    df_prod.apply(
        lambda row: (
            any(
                row["subCategory_imputed"] in subcat_list
                for subcat_list in subcategories_matching.values()
            )
            | any(
                row["subCategory_original"] in subcat_list
                for subcat_list in subcategories_matching.values()
            )
        ),
        axis=1,
    )
    & (df_prod["itemRd"] == 0)
)

# Ensure the required columns exist in df_prod
price_columns = [f"totalPrice_{key}" for key in subcategories_matching.keys() if f"totalPrice_{key}" in df_prod.columns]
amount_columns = [key for key in subcategories_matching.keys() if key in df_prod.columns]

if not price_columns or not amount_columns:
    raise ValueError("Required columns are missing in df_prod.")

# Compute the deferred amount for rows matching the mask
df_prod.loc[mask, "amountRayonDeferred"] = (
    df_prod.loc[mask, "totalPriceAfterDiscount"]
    / df_prod.loc[mask, price_columns].sum(axis=1).replace(0, 1)  # Avoid division by zero
    * df_prod.loc[mask, amount_columns].sum(axis=1)
)

In [36]:
df_prod.head(50)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.720404
6,2025-04-29,receipt,2,NaN,NaN,375G PIZZA BOLOGN.,375G PIZZA BOLOGN.,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
7,2025-04-29,receipt,2,NaN,NaN,410G PIZZA 3 VIAND,410G PIZZA 3 VIAND,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.138917
9,2025-04-29,receipt,1,NaN,NaN,20 OEUFS SOL,20 OEUFS SOL,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
10,2025-04-29,receipt,2,NaN,NaN,400G COLIN FISH.CH,400G COLIN FISH.CH,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
11,2025-04-29,receipt,4,NaN,NaN,BT 3X110MOUCH.CONF,BT 3X110MOUCH.CONF,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
12,2025-04-29,receipt,1,NaN,NaN,COCA-COLASSSCMINIC,COCA-COLASSSCMINIC,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.084826
14,2025-04-29,receipt,6,NaN,NaN,OY 1KG SPAGHETTI N,OY 1KG SPAGHETTI N,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
15,2025-04-29,receipt,2,NaN,NaN,12 RLX P.HYG.3P RO,12 RLX P.HYG.3P RO,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.152440
17,2025-04-29,receipt,1,NaN,NaN,132G SABLE CITRON,132G SABLE CITRON,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
18,2025-04-29,receipt,1,NaN,NaN,200G LARDONS F +30,200G LARDONS F +30,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,1.99,1.340000
19,2025-04-29,receipt,1,NaN,NaN,150G GATEAU FOURRE,150G GATEAU FOURRE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
20,2025-04-29,receipt,1,NaN,NaN,BARRE MINCEUR CERE,BARRE MINCEUR CERE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.243413
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,,5.5,...,MELON MOYEN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,,5.5,...,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,,5.5,...,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,,5.5,...,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.146439
27,2025-04-25,receipt,1,NaN,NaN,8X125G LAUTHENTIQ,8X125G LAUTHENTIQ,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
28,2025-04-25,receipt,1,NaN,NaN,PAVE LE PAIN RUST,PAVE LE PAIN RUST,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
29,2025-04-25,receipt,1,NaN,NaN,FLT 2KG PDT CQLP,FLT 2KG PDT CQLP,food,,5.5,...,FLT 2KG PDT CQLP,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
30,2025-04-25,receipt,1,NaN,NaN,16X125 NATUR DANON,16X125 NATUR DANON,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
31,2025-04-25,receipt,1,NaN,NaN,320G JB SP DD SSOG,320G JB SP DD SSOG,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
32,2025-04-25,receipt,1,NaN,NaN,CELERI BRANCHE,CELERI BRANCHE,food,,5.5,...,CELERI BRANCHE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
33,2025-04-25,receipt,1,NaN,NaN,BANANE CRF BIO,BANANE CRF BIO,food,,5.5,...,BANANE CRF BIO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
34,2025-04-25,receipt,1,NaN,NaN,POIVRON JAUNE,POIVRON JAUNE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.323326
35,2025-04-25,receipt,1,NaN,NaN,850G SKYR NATURE Y,850G SKYR NATURE Y,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
36,2025-04-25,receipt,1,NaN,NaN,125GX16 PAN0% PAN,125GX16 PAN0% PAN,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
37,2025-04-25,receipt,1,NaN,NaN,POMME GRANNY GROSS,POMME GRANNY GROSS,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.382772
38,2025-04-25,receipt,1,NaN,NaN,BRANDADE MORUE,BRANDADE MORUE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,8.89,NaN,NaN,1.360000
39,2025-04-25,receipt,1,NaN,NaN,BATAVIA PIECE,BATAVIA PIECE,food,,5.5,...,BATAVIA PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
40,2025-04-25,receipt,2,NaN,NaN,AVOCAT PIECE,AVOCAT PIECE,food,,5.5,...,AVOCAT PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
41,2025-04-25,receipt,1,NaN,NaN,MENTHE,MENTHE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.143539
42,2025-04-25,receipt,1,NaN,NaN,ORANGE DESSERT 2KG,ORANGE DESSERT 2KG,food,,5.5,...,ORANGE DESSERT 2KG,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
43,2025-04-25,receipt,1,NaN,NaN,PAIN CHOC PB X5 +,PAIN CHOC PB X5 +,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
44,2025-04-25,receipt,1,NaN,NaN,KIWI VERT PIECE,KIWI VERT PIECE,food,,5.5,...,KIWI VERT PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
45,2025-04-25,receipt,1,NaN,NaN,CHOU FLEUR PIECE,CHOU FLEUR PIECE,food,,5.5,...,CHOU FLEUR PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
46,2025-04-25,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.236333
47,2025-04-25,receipt,1,NaN,NaN,CONCOMBRE PIECE,CONCOMBRE PIECE,food,,5.5,...,CONCOMBRE PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
48,2025-04-25,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.127591
49,2025-04-25,receipt,1,NaN,NaN,1L HUILE FLEUR DE,1L HUILE FLEUR DE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN

In [90]:
df_prod[[f"totalPrice_{key}" for key in subcategories_matching.keys() if key in df_prod.columns]].sum(axis=1).head(30)

0      0.00
1      0.00
2      0.00
3      0.00
4      0.00
5     10.90
6      0.00
7      0.00
8     10.90
9      0.00
10     0.00
11     0.00
12     0.00
13    10.90
14     0.00
15     0.00
16    10.90
17     0.00
18     0.00
19     0.00
20     0.00
21    10.90
22     0.00
23     0.00
24     0.00
25     0.00
26     9.38
27     0.00
28     0.00
29     0.00
dtype: float64

In [95]:
df_prod

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred,totalTrueAmount
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,,5.5,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,,5.5,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5020,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,,10.0,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.75
5021,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.50
5022,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.99
5023,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.61
5024,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.18

In [37]:
df_prod.fillna(
    {
        "amountRayonDeferred": 0,
        "itemRd": 0
    },
    inplace=True,
)

In [38]:
df_prod['totalTrueAmount'] = df_prod['totalPriceAfterDiscount'] - df_prod['itemRd'] - df_prod['amountRayonDeferred']
df_prod[['dateKey', 'productLabel', 'totalPriceAfterDiscount', 'itemRd', 'amountRayonDeferred', 'totalTrueAmount']].head(30)

,dateKey,productLabel,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueAmount
0,2025-04-29,5X10 D FREEDENT ME,3.35,0.00,0.000000,3.350000
1,2025-04-29,KG POULET FERMIER,12.43,0.00,0.000000,12.430000
2,2025-04-29,750G OMEGA 3 DX SH,5.39,1.62,0.000000,3.770000
3,2025-04-29,3 RECH RUBAN MAGI,4.99,0.00,0.000000,4.990000
4,2025-04-29,132G BISC.COCO SSA,2.45,0.00,0.000000,2.450000
5,2025-04-29,KG TOMATE GRAP FR,5.86,0.00,0.720404,5.139596
6,2025-04-29,375G PIZZA BOLOGN.,4.14,0.00,0.000000,4.140000
7,2025-04-29,410G PIZZA 3 VIAND,4.72,0.00,0.000000,4.720000
8,2025-04-29,AUBERGINE VRAC,1.13,0.00,0.138917,0.991083
9,2025-04-29,20 OEUFS SOL,5.09,0.00,0.000000,5.090000
10,2025-04-29,400G COLIN FISH.CH,6.20,0.00,0.000000,6.200000
11,2025-04-29,BT 3X110MOUCH.CONF,12.41,0.00,0.000000,12.410000
12,2025-04-29,COCA-COLASSSCMINIC,3.65,0.00,0.000000,3.650000
13,2025-04-29,POIVRON ROUGE,0.69,0.00,0.084826,0.605174
14,2025-04-29,OY 1KG SPAGHETTI N,11.40,0.00,0.000000,11.400000
15,2025-04-29,12 RLX P.HYG.3P RO,7.80,0.00,0.000000,7.800000
16,2025-04-29,HARICOT VERT FIN,1.24,0.00,0.152440,1.087560
17,2025-04-29,132G SABLE CITRON,2.49,0.00,0.000000,2.490000
18,2025-04-29,200G LARDONS F +30,1.99,0.00,1.340000,0.650000
19,2025-04-29,150G GATEAU FOURRE,3.95,0.00,0.000000,3.950000
20,2025-04-29,BARRE MINCEUR CERE,8.99,0.00,0.000000,8.990000
21,2025-04-29,BQ TOM CERISE ALL,1.98,0.00,0.243413,1.736587
22,2025-04-25,MELON MOYEN,2.59,0.39,0.000000,2.200000
23,2025-04-25,MCH 500G OIGNON RO,2.99,0.45,0.000000,2.540000
24,2025-04-25,FILET AIL 3 TETES,3.19,0.47,0.000000,2.720000
25,2025-04-25,FLT 350G ECHALOTE,2.49,0.38,0.000000,2.110000
26,2025-04-25,COURGETTE,1.01,0.00,0.146439,0.863561
27,2025-04-25,8X125G LAUTHENTIQ,14.19,0.00,0.000000,14.190000
28,2025-04-25,PAVE LE PAIN RUST,2.05,0.00,0.000000,2.050000
29,2025-04-25,FLT 2KG PDT CQLP,3.07,0.46,0.000000,2.610000

In [39]:
df_prod.loc[df_prod.totalWeight > 0, "totalTrueUnitPrice"] = (
    df_prod.loc[df_prod.totalWeight > 0, "totalTrueAmount"]
    / df_prod.loc[df_prod.totalWeight > 0, "totalWeight"]
)

In [40]:
df_prod.query('productLabel.str.contains("saumon", case=False)')[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

,dateKey,productLabel,unitPrice,totalWeight,totalPrice,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueUnitPrice,totalTrueAmount
189,2025-03-29,FILET SAUMON FQC A,18.99,3.300,62.66,62.66,0.0,18.750000,13.306061,43.910000
249,2025-03-08,PAVE SAUMON,19.99,1.854,37.06,36.76,0.0,11.226210,13.772271,25.533790
557,2024-12-27,SAUMON ENTIER,8.90,2.913,25.93,25.93,0.0,0.000000,8.901476,25.930000
625,2024-12-15,420G PIZZA SAUMON,2.25,0.000,4.50,3.82,0.0,0.000000,NaN,3.820000
715,2024-11-19,TARTE SAUMON POIR.,3.89,0.000,7.78,5.45,0.0,0.000000,NaN,5.450000
728,2024-11-19,SAUMON ENTIER,9.99,1.998,19.96,19.96,0.0,2.256348,8.860687,17.703652
1022,2024-09-11,FILET SAUMON FQC A,11.99,5.268,63.17,63.17,0.0,6.508549,10.755780,56.661451
1867,2024-03-23,SAUMON ENTIER,11.99,4.904,58.80,58.80,0.0,0.000000,11.990212,58.800000
2555,2023-11-24,SAUMON ENTIER,9.99,2.808,28.05,28.05,0.0,0.000000,9.989316,28.050000
2833,2023-09-19,SAUMON ENTIER,9.99,2.430,24.28,24.28,0.0,0.000000,9.991770,24.280000
2874,2023-09-15,FILET SAUMON FQC A,12.99,2.218,28.81,28.81,0.0,0.000000,12.989179,28.810000
3055,2023-08-11,SAUMON ENTIER,9.99,5.700,56.94,56.94,0.0,0.000000,9.989474,56.940000
3069,2023-08-04,FILET SAUMON FQC A,13.99,2.310,32.32,32.32,0.0,0.000000,13.991342,32.320000
3986,2022-12-31,PAVE SAUMON,15.00,0.000,15.00,15.00,0.0,0.000000,NaN,15.000000
4758,2022-06-29,SAUMON SCE OSEILLE,4.95,0.000,4.95,4.95,0.0,0.000000,NaN,4.950000

In [55]:
df_prod.query('productLabel.str.contains("H&S", case=False)')[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

Empty DataFrame
Columns: [dateKey, productLabel, unitPrice, totalWeight, totalPrice, totalPriceAfterDiscount, itemRd, amountRayonDeferred, totalTrueUnitPrice, totalTrueAmount]
Index: []

In [54]:
df_prod.query('itemRd > 2')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred,totalTrueAmount,totalTrueUnitPrice
59,2025-04-17,receipt,1,NaN,NaN,396G SACH MEGA TO,396G SACH MEGA TO,food,,5.5,...,0.0,1.58,0.0,NaN,NaN,NaN,NaN,0.0,6.46,NaN
239,2025-03-15,receipt,2,NaN,NaN,RICORE RECHARGE 29,RICORE RECHARGE 29,food,,5.5,...,6.6,0.00,0.0,NaN,NaN,NaN,NaN,0.0,7.56,NaN
376,2025-02-01,receipt,1,NaN,NaN,70 COGNAC VS 40 HE,70 COGNAC VS 40 HE,other,,20.0,...,0.0,0.38,0.0,NaN,NaN,NaN,NaN,0.0,37.90,NaN
477,2025-01-14,receipt,1,NaN,NaN,FD ARIEL LIQ 3X22D,FD ARIEL LIQ 3X22D,other,,20.0,...,0.0,0.42,0.0,NaN,NaN,NaN,NaN,0.0,19.31,NaN
478,2025-01-14,receipt,1,NaN,NaN,FD ARIEL LIQ 3X22D,FD ARIEL LIQ 3X22D,other,,20.0,...,0.0,0.42,0.0,NaN,NaN,NaN,NaN,0.0,9.35,NaN
505,2025-01-05,order,1,8.700216e+12,7739158.0,Lessive Liquide Original ARIEL,lessive-liquide-original-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.32,NaN
508,2025-01-05,order,1,8.700216e+12,7746767.0,Lessive Liquide Ultra Détachant ARIEL,lessive-liquide-ultra-detachant-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.32,NaN
510,2025-01-05,order,1,8.700216e+12,7779560.0,Lessive Liquide Extra + Color Protection ARIEL,lessive-liquide-extra-color-protection-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,33.28,NaN
545,2024-12-31,receipt,1,NaN,NaN,2X6TR 2X215G SF N,2X6TR 2X215G SF N,food,,5.5,...,2.9,0.00,0.0,NaN,NaN,NaN,NaN,0.0,15.39,NaN
847,2024-10-19,order,1,4.549651e+10,7749119.0,Jeu Pass Circuits additionnels Mario Kart 8 De...,jeu-pass-circuits-additionnels-mario-kart-8-de...,other,Nintendo Switch,NaN,...,0.0,1.10,0.0,NaN,NaN,NaN,NaN,0.0,19.49,NaN
899,2024-10-06,receipt,2,NaN,NaN,KALANCHOE COUPE DE,KALANCHOE COUPE DE,other,,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,15.98,NaN
1067,2024-09-06,receipt,2,NaN,NaN,2X75ML DENT S.G CA,2X75ML DENT S.G CA,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.25,NaN
1075,2024-09-06,receipt,2,NaN,NaN,2X75ML PSA GENC.EM,2X75ML PSA GENC.EM,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.26,NaN
1104,2024-09-06,receipt,2,NaN,NaN,2X75ML DENT PSA NE,2X75ML DENT PSA NE,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.10,NaN
1498,2024-06-15,receipt,3,NaN,NaN,3X75ML DENT WN TP,3X75ML DENT WN TP,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.91,NaN
1602,2024-05-24,receipt,1,NaN,NaN,3X150G LT3 DELIC L,3X150G LT3 DELIC L,food,,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.36,NaN

In [65]:
df_prod.query('productLabel.str.contains("Citrus", case=False)')

Empty DataFrame
Columns: [dateKey, recordType, countVisits, ean, cdbase, productLabel, slugProductLabel, category, subCategory_original, vatPercentage, totalQuantity, totalWeight, unitPrice, totalPrice, totalImmediateDiscount, totalPriceAfterDiscount, subCategory_imputed, date, itemLabel, itemRd, matchedLabel, date_loyalty_rayon, ART RAYON BOUCHERIE TVA 5,5, ART RAYON FRUITS LEG TVA 5,5, ART RAYON POISSONNERIE TVA 5,5, totalPrice_ART RAYON FRUITS LEG TVA 5,5, totalPrice_ART RAYON POISSONNERIE TVA 5,5, totalPrice_ART RAYON BOUCHERIE TVA 5,5, totalPrice_ART RAYON CHARCUTERIE TVA 5,5, amountRayonDeferred, totalTrueAmount, totalTrueUnitPrice]
Index: []

[0 rows x 32 columns]

In [49]:
df_loyalty.query("date == @pd.to_datetime('2024-05-09')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
219,63092555004,2024-05-09,0.0,-20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df_loyalty.query('itemLabel.notna() & itemLabel.str.contains("Citrus", case=False)')

Empty DataFrame
Columns: [operationId, date, earned, burned, itemLabel, promotionLabel, itemRd, loyaltyOperation, embeddingLabel, matchedLabel1, similarity_score1, matchedLabelFuzzy, matchedLabel2, similarity_score2, matchedLabel]
Index: []

In [67]:
df_loyalty.itemLabel.unique()

array(['20 OEUFS DJP POULE AU SOL CRF', 'BANANE CRF BIO MH 5 FRUITS',
       '1KG COUSCOUS MOYEN CRF', nan, 'FLT 500G CITRON VERT',
       '1KG FROMAGE FRAIS 0%MG CRF CLA', 'OIGNON ROUGE BOTTE',
       'PAIN COMPLET CRF BIO 400G', 'ART RAYON FRUITS LEG TVA 5,5',
       'ST 200G HARICOT.MUNGO 0,99', 'ARTICHAUT PIECE',
       'FLT ECHALOTE 500G SIMPL FR', 'FILET AIL 3 TETES',
       '16X125G YRT FRUIT 0% CRF CLASS', 'RADIS ROSE BOTTE',
       'FLT 350G ECHALOTE FR', 'ART RAYON POISSONNERIE TVA 5,5',
       '125G MOZZARELLA VACHE', '16X125G BIF NATURE ACTIVIA OD',
       '2X75ML DENT PSA NETT INTENS OB', '2X75ML PSA GENC&EMAIL ORIG OB',
       'AG SCOL OXFORD FLOWERS 12X18', '2X75ML DENT S&G CALM ORIGIN OB',
       '500G LUTTI HAPPY FIZZ', 'SWITCH SET MARIO KART 8 PASS C',
       'FLT 1,5KG ORANGE DESSERT CRF', 'BQ 200G CHAMPIGNONS BRUN FQC',
       'BROCOLI PCE FR', 'KIWI VERT PIECE', 'BATAVIA SALADE PIECE',
       'BQ250G TT CERISE ALL SIMPL HF', 'CITRON VERT PIECE',
       'AVOCAT PIECE', 'KALANCHOE COUPE DE 23',
       '1L BOISSON SOJA NATUR CARF BIO', 'POMELO PIECE',
       'ST 1,5KG POMME GALA FR', 'RUBAN TRANSPT 550 19MMX33M',
       'MAIS SANS SUCRE AJOUTE BOITE 3', '3X1/4 MAIS SS AJOUTE CRF CLASS',
       'ART RAYON BOUCHERIE TVA 5,5', '2X6TR 2X215G SF NOR',
       'FLT 2KG ORANGE DESSERT CRF HF', 'KAKI PIECE',
       'POTIMARRON PIECE FR', '750G OMEGA 3 DX ST HUBERT',
       'MELON MOYEN PIECE', 'CHOU FLEUR  PIECE',
       'MCH 500G OIGNON ROUGE FQC FR', 'FLT 350G ECHALOTE FQC FR',
       'MENTHE FRAICHE BOTTE', 'FLT 2KG PDT VP BL CQLP FR',
       'BATAVIA PIECE', 'CONCOMBRE PIECE', 'BASILIC FRAIS BOTTE',
       "396G SACH MEGA T'OEUF PETIL", 'PERSIL PLAT FRAIS BOTTE MAX',
       'FLT 6 BULBES OIGNON JN FR', 'ST 400G EPINARD FR',
       'CHOU ROUGE PIECE', '1KG FILET POULET PLK', 'KIWI VERT FQC PIECE',
       'FLT2KG PDT CONS FPP CRF FR', '300G BISCOT.GERM.BLE BIO CRF',
       '1L BOISSON RIZ NOISET CRF BIO', 'ACETONE 1L',
       'BQ400G TOM CERISE ALL IMP', 'PQ 1KG FARINE TYPE 65 CRF BIO',
       'FLT2KG PDT CONS FPP FQC', 'ARIEL LIQ 3X22D ACTIVE',
       'LTX3 ARIEL LIQ 22D UNSTOPPABLE', 'ARIEL LIQUIDE 34D ORIGINAL',
       'ARIEL LIQUIDE 31D PROTECTION', 'ARIEL LIQUIDE 31D ULTRA',
       '1X8L FF BP MATIN LEGER ECREME', 'PCE CHOU BROCOLIS CRF CEE',
       'ST 500G BETTERAVE FQC AGR', 'BANANE 5 DOIGTS 0.99 HF',
       '1KG FARINE BLE T45 CRF CLASSIC', '1KG FARINE BLE FLUID T45 CRF C',
       '3X75ML DENT WN TP SENS SIGNAL', '4X138G CROUSTILLE EMTL. BELIN',
       'PDA PAVE CRF BIO 500G', 'FLT 2KG ORANGE DESSERT FQC HF',
       'FLT 2KG PDT BLC VAP FQC FR', 'ST 2PCES MAIS DOUX HF',
       'PAIC BI ACTIV SEL MINERAL2X750', '12X125G YAOURTS PAT LA LAIT',
       'FLT 2KG PDT FRITE FQC FR', '70CL COGNAC VS 40% HENNESSY',
       'ST 500G BETTERAV PRIM FQC AGRO', 'MANCH. 500G OIGNON ROUGE FR',
       'FLT 1 KG PDT CONSO 0.99 SIMPL', '20X OEUFS DJP SOL CRF  CLASSIC',
       'SALADE BATAVIA PIECE', '400 ML LT CORPS NUTRI ARG LPM',
       '550G PAIN SANDW.CEREAL CRF CLA', 'CORIANDRE FRAIS BOTTE',
       '125G MOZZARELLA BUFALA BIO CRF', 'FLT 2KG PDT BLC VAP CRF FR',
       '100G GRANA PADANO RAPE AOP CRF', 'MELON PETIT PIECE',
       'RICORE RECHARGE 290G'], dtype=object)

In [70]:
df_loyalty.query("date == @pd.to_datetime('2024-05-09')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
219,63092555004,2024-05-09,0.0,-20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df_prod.query("dateKey == @pd.to_datetime('2024-05-09')")[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

,dateKey,productLabel,unitPrice,totalWeight,totalPrice,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueUnitPrice,totalTrueAmount
1653,2024-05-09,KIWI VERT PIECE,0.59,0.000,2.36,2.00,0.0,0.0,NaN,2.00
1654,2024-05-09,750G CASSONADE,2.69,0.000,2.69,2.69,0.0,0.0,NaN,2.69
1655,2024-05-09,BT 3X110MOUCH.CONF,3.89,0.000,7.78,7.78,0.0,0.0,NaN,7.78
1656,2024-05-09,24 PS EXTRA LONG C,1.55,0.000,1.55,1.55,0.0,0.0,NaN,1.55
1657,2024-05-09,POIVRON ROUGE,3.99,0.514,2.05,2.05,0.0,0.0,3.988327,2.05
1658,2024-05-09,OUTILS 13-1 BOSCH,17.99,0.000,17.99,3.00,0.0,0.0,NaN,3.00
1659,2024-05-09,AVOCAT PIECE,1.19,0.000,2.38,1.80,0.0,0.0,NaN,1.80
1660,2024-05-09,KG POMME FUJI FQC,1.99,1.151,2.29,2.29,0.0,0.0,1.989574,2.29
1661,2024-05-09,226G PICANTE SALSA,2.99,0.000,5.98,4.18,0.0,0.0,NaN,4.18
1662,2024-05-09,SOURIS TIPP EX X2,3.79,0.000,3.79,3.79,0.0,0.0,NaN,3.79
1663,2024-05-09,PRESIDENT LE BLEU,3.39,0.000,3.39,3.39,0.0,0.0,NaN,3.39
1664,2024-05-09,6X1.5L CRISTALINE,1.14,0.000,1.14,1.14,0.0,0.0,NaN,1.14
1665,2024-05-09,KNACKI ORIGINAL PO,1.99,0.000,1.99,1.99,0.0,0.0,NaN,1.99
1666,2024-05-09,NESCAFE SPEC.FILTR,6.89,0.000,13.78,12.28,0.0,0.0,NaN,12.28
1667,2024-05-09,SH 2EN1 CLASSIC 62,11.09,0.000,11.09,11.09,0.0,0.0,NaN,11.09
1668,2024-05-09,FEUTRE POINT 88 AS,2.65,0.000,2.65,2.65,0.0,0.0,NaN,2.65
1669,2024-05-09,COURGETTE,2.49,0.799,1.99,1.99,0.0,0.0,2.490613,1.99
1670,2024-05-09,10 PORTIONS TARTAR,2.19,0.000,2.19,2.19,0.0,0.0,NaN,2.19
1671,2024-05-09,TORTI CHIPS PAPRIK,3.55,0.000,7.10,4.98,0.0,0.0,NaN,4.98
1672,2024-05-09,5X10 D FREEDENT WH,2.35,0.000,4.70,3.52,0.0,0.0,NaN,3.52
1673,2024-05-09,2X75G EMINCES DE P,2.99,0.000,2.99,2.99,0.0,0.0,NaN,2.99
1674,2024-05-09,KG TOMATE GRAP FR,2.49,0.434,1.08,1.08,0.0,0.0,2.488479,1.08
1675,2024-05-09,305G RAVIOLI 4 FRO,2.69,0.000,2.69,2.69,0.0,0.0,NaN,2.69
1676,2024-05-09,ORANGE DESSERT 2KG,3.19,0.000,3.19,3.19,0.0,0.0,NaN,3.19
1677,2024-05-09,MENTHE,0.99,0.000,0.99,0.99,0.0,0.0,NaN,0.99
1678,2024-05-09,6T F BLC PLT DORE,2.19,0.000,2.19,2.19,0.0,0.0,NaN,2.19
1679,2024-05-09,POIRE CONFERENCE,3.49,0.888,3.10,3.10,0.0,0.0,3.490991,3.10