# Dataframe loading

This notebook loads the two dataframes of purchased products and loyalty items.
For things to be weighted, aggregation must be done for better readability.

In [8]:
import sys
sys.path.append("..")

In [9]:
import pandas as pd

In [55]:
df_prod = pd.read_csv('../data/20250601-carrefour_products.csv', parse_dates=['dateKey'])
df_loyalty = pd.read_csv('../data/20250601-carrefour_loyalty_extended.csv', parse_dates=['date'])
display(df_prod)
display(df_loyalty)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalAmountImmediateDiscount,totalPriceAfterDiscount
0,2025-05-31,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,NaN,5.5,1,0.000,3.19,3.19,0.00,NaN,3.19
1,2025-05-31,receipt,1,NaN,NaN,POIREAU VRAC,POIREAU VRAC,food,NaN,5.5,1,0.462,2.99,1.38,0.00,NaN,1.38
2,2025-05-31,receipt,2,NaN,NaN,5X10 D FREEDENT MY,5X10 D FREEDENT MY,other,NaN,20.0,2,0.000,2.99,5.98,-1.79,NaN,4.19
3,2025-05-31,receipt,1,NaN,NaN,BPARIS JAMBON,BPARIS JAMBON,food,NaN,5.5,1,0.000,2.95,2.95,0.00,NaN,2.95
4,2025-05-31,receipt,1,NaN,NaN,BANANE CRF BIO,BANANE CRF BIO,food,NaN,5.5,1,0.000,1.99,1.99,0.00,NaN,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,NaN,5.5,2,0.000,1.59,3.18,0.00,NaN,3.18
5168,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,NaN,10.0,1,0.000,1.75,1.75,0.00,NaN,1.75
5169,2022-04-25,receipt,1,NaN,NaN,BARRE CEREAL.CHOCO,BARRE CEREAL.CHOCO,food,NaN,5.5,1,0.000,1.32,1.32,0.00,NaN,1.32
5170,2022-04-25,receipt,1,NaN,NaN,25 SACS CONGEL 1L,25 SACS CONGEL 1L,other,NaN,20.0,1,0.000,1.85,1.85,0.00,NaN,1.85
5171,2022-04-25,receipt,1,NaN,NaN,ARTICHAUT BLANC PC,ARTICHAUT BLANC PC,food,NaN,5.5,2,0.000,1.65,3.30,0.00,NaN,3.30

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP POULE,0.844788,BANANE CRF BIO,0.610679,20 OEUFS DJP POULE,20 OEUFS DJP POULE,20 OEUFS DJP POULE AU SOL CRFPaiement en caisse,20 OEUFS DJP PLE A
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,BQ CROQUE BB FROM,0.623993,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-3.55873778e-02 6.42536953e-02 -1.99550646e-...,1KG COUSCOUS MOYEN,0.899923,CHAUSSONS AUX POMM,0.611897,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN CRFPaiement en caisse,NaN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Yaourt aux fruits jaunes pêche abricot poire a...,0.619123,Yaourt aux fruits rouges fraise framboise ceri...,Bananes Bio CARREFOUR BIO,BANANE CRF BIO MH 5 FRUITSPaiement en ligne,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ART RAYON FRUITS LEG TVA 5,5Paiement en caisse",NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ART RAYON POISSONNERIE TVA 5,5Paiement en caisse",NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,[-6.34368062e-02 7.53262192e-02 -9.41641927e-...,CHOU FLEUR PIECE,1.000000,1L HUILE FLEUR DE,0.695785,CHOU FLEUR PIECE,CHOU FLEUR PIECE,CHOU FLEUR PIECEPaiement en caisse,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,TOMATE GRAPPE,0.572408,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Merging receipt details with loyalty data

In [61]:
df_loyalty_amounts = df_loyalty[['date', 'itemLabel', 'itemRd', 'matchedLabel']]

In [56]:
df_loyalty.query('(matchedLabel1.notna()) and (matchedLabel1 != mostFrequentMatchedLabel1)')

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
0,64070450536,2024-09-28,0.66,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP POULE,0.844788,BANANE CRF BIO,0.610679,20 OEUFS DJP POULE,20 OEUFS DJP POULE,20 OEUFS DJP POULE AU SOL CRFPaiement en caisse,20 OEUFS DJP PLE A
2,64063052302,2024-09-24,0.30,0.0,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-3.55873778e-02 6.42536953e-02 -1.99550646e-...,1KG COUSCOUS MOYEN,0.899923,CHAUSSONS AUX POMM,0.611897,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN CRFPaiement en caisse,NaN
6,64068321557,2024-09-13,8.32,0.0,1KG FROMAGE FRAIS 0%MG CRF CLA,NaN,0.27,Paiement en caisse,[-7.89078232e-03 4.75184172e-02 2.95940619e-...,1KG FROMAGE FRAIS,0.914593,PAIN COMPLET CRF B,0.661725,1KG FROMAGE FRAIS,1KG FROMAGE FRAIS,1KG FROMAGE FRAIS 0%MG CRF CLAPaiement en caisse,NaN
7,64068321557,2024-09-13,8.32,0.0,OIGNON ROUGE BOTTE,NaN,0.40,Paiement en caisse,[-5.34472689e-02 6.90731257e-02 -2.66275071e-...,BOTTE OIGNON ROUGE,0.969702,RADIS ROSE BOTTE,0.795645,BOTTE OIGNON ROUGE,BOTTE OIGNON ROUGE,OIGNON ROUGE BOTTEPaiement en caisse,NaN
8,64068321557,2024-09-13,8.32,0.0,PAIN COMPLET CRF BIO 400G,NaN,0.68,Paiement en caisse,[-6.05254024e-02 1.02311485e-02 -1.37503650e-...,PAIN COMPLET CRF B,0.898617,360G PNE CORNICHON,0.564542,PAIN COMPLET CRF B,PAIN COMPLET CRF B,PAIN COMPLET CRF BIO 400GPaiement en caisse,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,65142938374,2025-03-29,21.60,0.0,CORIANDRE FRAIS BOTTE,NaN,0.11,Paiement en caisse,[-4.34893593e-02 7.36030862e-02 -1.01737231e-...,CORIANDRE B,0.750697,KG TOMATE GRAP FR,0.630726,CORIANDRE B,CORIANDRE B,CORIANDRE FRAIS BOTTEPaiement en caisse,NaN
310,65151304770,2025-03-22,4.53,0.0,125G MOZZARELLA BUFALA BIO CRF,NaN,0.77,Paiement en caisse,[-5.27739860e-02 1.23036979e-02 -3.04408427e-...,125G MOZZARELLA BU,0.890647,BQ TOM CERISE ALL,0.593580,125G MOZZARELLA BU,125G MOZZARELLA BU,125G MOZZARELLA BUFALA BIO CRFPaiement en caisse,NaN
314,65151304770,2025-03-22,4.53,0.0,100G GRANA PADANO RAPE AOP CRF,NaN,0.58,Paiement en caisse,[-1.15412124e-03 2.73329541e-02 -3.62889804e-...,100G GRANA PADANO,0.875327,BANANE CRF BIO,0.659612,100G GRANA PADANO,100G GRANA PADANO,100G GRANA PADANO RAPE AOP CRFPaiement en caisse,NaN
322,65146373916,2025-03-15,10.62,0.0,MELON PETIT PIECE,NaN,0.22,Paiement en caisse,[-5.21185473e-02 3.92801538e-02 -4.22733277e-...,MELON PETIT,0.973049,BATAVIA PIECE,0.649464,MELON PETIT,MELON PETIT,MELON PETIT PIECEPaiement en caisse,NaN
324,65146373916,2025-03-15,10.62,0.0,RICORE RECHARGE 290G,NaN,3.24,Paiement en caisse,[-3.72729748e-02 3.66675593e-02 1.28476415e-...,RICORE RECHARGE 29,0.886762,20+12 GRT RLX PH,0.578761,RICORE RECHARGE 29,RICORE RECHARGE 29,RICORE RECHARGE 290GPaiement en caisse,NaN

In [57]:
df_loyalty.query('(matchedLabel1.notna()) and (similarity_score1 < 0.7)')

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
50,64635649471,2024-10-07,0.46,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Œufs frais poules au sol CARREFOUR CLASSIC',0.588981,Papier toilette Ultra Confort CARREFOUR ESSENTIAL,0.519383,NaN,Œufs frais poules au sol CARREFOUR CLASSIC',20 OEUFS DJP POULE AU SOL CRFPaiement en ligne,Œufs frais poules au sol CARREFOUR CLASSIC'
72,63726335992,2024-08-26,0.82,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Œufs frais poules au sol CARREFOUR CLASSIC',0.588981,Huile de pépins de raisin CARREFOUR CLASSIC',0.574062,Boisson végétale au soja nature Bio CARREFOUR...,Œufs frais poules au sol CARREFOUR CLASSIC',20 OEUFS DJP POULE AU SOL CRFPaiement en ligne,Œufs frais poules au sol CARREFOUR CLASSIC'
77,63724848170,2024-08-18,4.45,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.60,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,250G RICOTTA CRF C,0.598712,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
82,63726339040,2024-08-09,1.74,0.0,RUBAN TRANSPT 550 19MMX33M,NaN,0.44,Paiement en ligne,[ 4.96372068e-03 1.00522593e-01 -2.75683161e-...,Ruban adhésif 33 x 19mm SCOTCH,0.665986,Sucre roux pure canne blond BLONVILLIERS,0.574532,NaN,Ruban adhésif 33 x 19mm SCOTCH,RUBAN TRANSPT 550 19MMX33MPaiement en ligne,NaN
84,63726339040,2024-08-09,1.74,0.0,MAIS SANS SUCRE AJOUTE BOITE 3,NaN,0.54,Paiement en ligne,[-3.60063277e-02 2.51771137e-02 -7.07581788e-...,Maïs sans sucres ajoutés CARREFOUR CLASSIC',0.596173,Maïs sans sucres ajoutés CARREFOUR CLASSIC',0.596173,Pain de mie American sandwich complet sans suc...,Maïs sans sucres ajoutés CARREFOUR CLASSIC',MAIS SANS SUCRE AJOUTE BOITE 3Paiement en ligne,NaN
89,63714189452,2024-08-03,1.64,0.0,MAIS SANS SUCRE AJOUTE BOITE 3,NaN,0.39,Paiement en caisse,[-3.60063277e-02 2.51771137e-02 -7.07581788e-...,MAIS SANS SUCRE AJ,0.690282,FILET AIL 3 TETES,0.632093,MAIS SANS SUCRE AJ,MAIS SANS SUCRE AJ,MAIS SANS SUCRE AJOUTE BOITE 3Paiement en caisse,NaN
97,65144522536,2024-12-20,3.43,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.30,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,KG TOMATE GRAP FR,0.573115,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
144,65138667969,2025-04-12,7.08,0.0,ST 400G EPINARD FR,NaN,0.50,Paiement en caisse,[-3.11841834e-02 8.37109610e-02 -3.08545865e-...,ST EPINARD A CUIRE,0.699588,CAROTTE VRAC,0.600725,NaN,ST EPINARD A CUIRE,ST 400G EPINARD FRPaiement en caisse,NaN
205,63089401410,2024-05-24,4.56,0.0,1X8L FF BP MATIN LEGER ECREME,NaN,4.08,Paiement en ligne,[-2.06623878e-02 5.01386821e-02 -4.18329276e-...,PANIER LEGUMES X1,0.639516,3X150G LT3 DELIC L,0.624134,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,1X8L FF BP MATIN LEGER ECREMEPaiement en ligne,NaN
223,63089578206,2024-06-27,0.94,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Crêpes jambon emmental CARREFOUR CLASSIC',0.597213,Œufs frais poules au sol CARREFOUR CLASSIC',0.588981,Boisson végétale au soja nature Bio CARREFOUR BIO,Œufs frais poules au sol CARREFOUR CLASSIC',20 OEUFS DJP POULE AU SOL CRFPaiement en ligne,Œufs frais poules au sol CARREFOUR CLASSIC'
246,65146408845,2025-02-28,1.41,0.0,ST 2PCES MAIS DOUX HF,NaN,0.90,Paiement en caisse,[-3.83969098e-02 6.32952377e-02 3.65249231e-...,MAIS DOUX,0.613553,9X20G SP.FROM.ST M,0.601174,MAIS DOUX,MAIS DOUX,ST 2PCES MAIS DOUX HFPaiement en caisse,NaN
253,65152187346,2025-02-18,6.77,0.0,PAIC BI ACTIV SEL MINERAL2X750,NaN,1.49,Paiement en ligne,[-3.91683094e-02 1.14902575e-02 -5.32393716e-...,Liquide Vaisselle Vinaigre et Sel Minéral Bi-A...,0.675284,Artichaut blanc,0.516956,Liquide Vaisselle Vinaigre et Sel Minéral Bi-A...,Liquide Vaisselle Vinaigre et Sel Minéral Bi-A...,PAIC BI ACTIV SEL MINERAL2X750Paiement en ligne,NaN
257,65152187346,2025-02-18,6.77,0.0,PCE CHOU BROCOLIS CRF CEE,NaN,0.38,Paiement en ligne,[-8.94991606e-02 8.05692002e-02 -8.74599218e-...,Brocoli,0.656124,Pizza Royale,0.553239,Brocoli,Brocoli,PCE CHOU BROCOLIS CRF CEEPaiement en ligne,NaN
258,65152187346,2025-02-18,6.77,0.0,ARTICHAUT PIECE,NaN,0.44,Paiement en ligne,[-2.10595597e-02 8.66309553e-02 -2.59835087e-...,Artichaut blanc,0.678092,Mouchoirs Confort,0.559762,NaN,Artichaut blanc,ARTICHAUT PIECEPaiement en ligne,NaN
285,63234561756,2024-07-26,9.24,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.39,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,POMME GRANNY VRAC,0.609958,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO

In [53]:
df_loyalty.query('itemLabel.notna() and itemLabel.str.contains("MATIN LEGER")')

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
205,63089401410,2024-05-24,4.56,0.0,1X8L FF BP MATIN LEGER ECREME,NaN,4.08,Paiement en ligne,[-2.06623878e-02 5.01386821e-02 -4.18329276e-...,PANIER LEGUMES X1,0.639516,3X150G LT3 DELIC L,0.624134,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,PANIER LEGUMES X1,1X8L FF BP MATIN LEGER ECREMEPaiement en ligne,PANIER LEGUMES X1

In [54]:
df_loyalty.query('date == @pd.to_datetime("2024-05-24")')

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
204,63093807786,2024-05-24,0.00,-22.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,63089401410,2024-05-24,4.56,0.00,1X8L FF BP MATIN LEGER ECREME,NaN,4.08,Paiement en ligne,[-2.06623878e-02 5.01386821e-02 -4.18329276e-...,PANIER LEGUMES X1,0.639516,3X150G LT3 DELIC L,0.624134,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,PANIER LEGUMES X1,1X8L FF BP MATIN LEGER ECREMEPaiement en ligne,PANIER LEGUMES X1
206,63089401410,2024-05-24,4.56,0.00,1L BOISSON SOJA NATUR CARF BIO,NaN,0.48,Paiement en ligne,[-4.70703021e-02 1.43808890e-02 -2.76396256e-...,Boisson végétale au soja nature Bio CARREFOUR BIO,0.863731,Boisson Red Ace CARREFOUR SELECTION,0.667967,BANANE CRF BIO MH,Boisson végétale au soja nature Bio CARREFOUR BIO,1L BOISSON SOJA NATUR CARF BIOPaiement en ligne,Boisson végétale au soja nature Bio CARREFOUR...
207,63071351432,2024-05-24,0.98,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.30,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO MH,0.892898,Nectar de goyave CARREFOUR SELECTION,0.641912,BANANE CRF BIO MH,BANANE CRF BIO MH,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
208,63071351432,2024-05-24,0.98,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.68,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP PLE A,0.848876,CROQUE EMMENTAL,0.601091,GINGEMBRE VRAC AU,20 OEUFS DJP PLE A,20 OEUFS DJP POULE AU SOL CRFPaiement en caisse,20 OEUFS DJP PLE A

In [49]:
df_loyalty.query('(matchedLabel1.notna()) and  (matchedLabel1 != matchedLabelFuzzy) and (similarity_score1 > 0.7)')

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
3,64072667140,2024-09-20,0.20,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Yaourt aux fruits jaunes pêche abricot poire a...,0.619123,Yaourt aux fruits rouges fraise framboise ceri...,Bananes Bio CARREFOUR BIO,BANANE CRF BIO MH 5 FRUITSPaiement en ligne,Bananes Bio CARREFOUR BIO
12,64068321557,2024-09-13,8.32,0.0,FLT ECHALOTE 500G SIMPL FR,NaN,0.29,Paiement en caisse,[ 1.26887113e-02 1.16611840e-02 4.47784504e-...,FLT ECHALOT SIMPL,0.918302,FLT 350G ECHALOTE,0.884147,FLT 350G ECHALOTE,FLT ECHALOT SIMPL,FLT ECHALOTE 500G SIMPL FRPaiement en caisse,FLT ECHALOT SIMPL
25,64072492932,2024-09-07,5.20,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.40,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Mouchoirs Confort CARREFOUR SOFT,0.584913,NaN,Bananes Bio CARREFOUR BIO,BANANE CRF BIO MH 5 FRUITSPaiement en ligne,Bananes Bio CARREFOUR BIO
29,64068320573,2024-09-06,17.03,0.0,2X75ML PSA GENC&EMAIL ORIG OB,NaN,4.24,Paiement en caisse,[-1.09107262e-02 5.68357967e-02 -2.19687540e-...,2X75ML PSA GENC.EM,0.798994,20 OEUFS SOL,0.634638,2X75ML DENT S.G CA,2X75ML PSA GENC.EM,2X75ML PSA GENC&EMAIL ORIG OBPaiement en caisse,2X75ML PSA GENC.EM
43,64625112459,2024-10-19,5.58,0.0,BATAVIA SALADE PIECE,NaN,0.19,Paiement en caisse,[-6.11950867e-02 7.64010102e-02 -6.13852218e-...,BATAVIA PIECE,0.931950,KIWI VERT PIECE,0.652601,AVOCAT PIECE,BATAVIA PIECE,BATAVIA SALADE PIECEPaiement en caisse,BATAVIA PIECE
71,63726335992,2024-08-26,0.82,0.0,1L BOISSON SOJA NATUR CARF BIO,NaN,0.36,Paiement en ligne,[-4.70703021e-02 1.43808890e-02 -2.76396256e-...,Boisson végétale au soja nature Bio CARREFOUR...,0.863731,Boisson Mojito sans alcool CARREFOUR SELECTION,0.645852,Boisson Mojito sans alcool CARREFOUR SELECTION,Boisson végétale au soja nature Bio CARREFOUR...,1L BOISSON SOJA NATUR CARF BIOPaiement en ligne,Boisson végétale au soja nature Bio CARREFOUR...
73,63726165061,2024-08-23,0.20,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Coriandre fraîche,0.584389,NaN,Bananes Bio CARREFOUR BIO,BANANE CRF BIO MH 5 FRUITSPaiement en ligne,Bananes Bio CARREFOUR BIO
83,63726339040,2024-08-09,1.74,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.40,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Huile de pépins de raisin CARREFOUR CLASSIC',0.637446,Yaourt aux fruits jaunes pêche abricot poire a...,Bananes Bio CARREFOUR BIO,BANANE CRF BIO MH 5 FRUITSPaiement en ligne,Bananes Bio CARREFOUR BIO
113,65144285331,2025-04-25,6.49,0.0,FLT 2KG ORANGE DESSERT CRF HF,NaN,0.52,Paiement en caisse,[ 8.61066859e-03 5.36054671e-02 -7.54230330e-...,ORANGE DESSERT 2KG,0.870981,FLT 2KG PDT CQLP,0.748707,FLT 350G ECHALOTE,ORANGE DESSERT 2KG,FLT 2KG ORANGE DESSERT CRF HFPaiement en caisse,ORANGE DESSERT 2KG
164,65149585512,2025-01-28,7.22,0.0,BQ400G TOM CERISE ALL IMP,NaN,0.44,Paiement en caisse,[-3.25766369e-03 5.27753085e-02 -2.31762584e-...,TOMATE CERISE ALL,0.737112,TOMATE GRAPPE,0.626395,NaN,TOMATE CERISE ALL,BQ400G TOM CERISE ALL IMPPaiement en caisse,TOMATE CERISE ALL
186,65143918436,2025-01-14,66.51,0.0,LTX3 ARIEL LIQ 22D UNSTOPPABLE,NaN,19.90,Paiement en caisse,[-0.0168325 0.06098599 0.00548893 0.074870...,FD LTX3 ARIEL LIQ,0.899664,FD ARIEL LIQ 3X22D,0.851357,FD ARIEL LIQ 3X22D,FD LTX3 ARIEL LIQ,LTX3 ARIEL LIQ 22D UNSTOPPABLEPaiement en caisse,FD LTX3 ARIEL LIQ
206,63089401410,2024-05-24,4.56,0.0,1L BOISSON SOJA NATUR CARF BIO,NaN,0.48,Paiement en ligne,[-4.70703021e-02 1.43808890e-02 -2.76396256e-...,Boisson végétale au soja nature Bio CARREFOUR BIO,0.863731,Boisson Red Ace CARREFOUR SELECTION,0.667967,BANANE CRF BIO MH,Boisson végétale au soja nature Bio CARREFOUR BIO,1L BOISSON SOJA NATUR CARF BIOPaiement en ligne,Boisson végétale au soja nature Bio CARREFOUR...
208,63071351432,2024-05-24,0.98,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.68,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP PLE A,0.848876,CROQUE EMMENTAL,0.601091,GINGEMBRE VRAC AU,20 OEUFS DJP PLE A,20 OEUFS DJP POULE AU SOL CRFPaiement en caisse,20 OEUFS DJP PLE A
226,63062504666,2024-06-20,0.98,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.68,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP PLE A,0.848876,BANANE CRF BIO,0.610679,LA LAITIERE RIZ AU,20 OEUFS DJP PLE A,20 OEUFS DJP POULE AU SOL CRFPaiement en caisse,20 OEUFS DJP PLE A
240,65146229813,2025-02-28,8.80,0.0,FLT 2KG ORANGE DESSERT FQC HF,NaN,0.52,Paiement en caisse,[-2.01599067e-03 6.38145506e-02 -1.46350022e-...,ORANGE DESSERT 2KG,0.878241,PDT VAP BL 2KG FQC,0.626695,CAROTTE FQC VRAC,ORANGE DESSERT 2KG,FLT 2KG ORANGE DESSERT FQC HFPaiement en caisse,ORANGE DESSERT 2KG
277,63234561756,2024-07-26,9.24,0.0,MANCH. 500G OIGNON ROUGE FR,NaN,0.60,Paiement en caisse,[-5.96847869e-02 5.21549657e-02 -6.43418124e-...,500G OIGNON RGE FR,0.838135,COURGETTE,0.600366,KG TOMATE GRAP FR,500G OIGNON RGE FR,MANCH. 500G OIGNON ROUGE FRPaiement en caisse,500G OIGNON RGE FR
280,63234561756,2024-07-26,9.24,0.0,FLT 1 KG PDT CONSO 0.99 SIMPL,NaN,0.24,Paiement en caisse,[-6.37520943e-03 5.02252914e-02 -4.97279204e-...,FLT 1KG P.DE TERRE,0.738860,FLT 350G ECHALOTE,0.671984,KG TOMATE GRAP FR,FLT 1KG P.DE TERRE,FLT 1 KG PDT CONSO 0.99 SIMPLPaiement en caisse,FLT 1KG P.DE TERRE
284,63234561756,2024-07-26,9.24,0.0,20X OEUFS DJP SOL CRF CLASSIC,NaN,0.46,Paiement en caisse,[ 0.01215151 0.03599822 0.00197543 0.027010...,20 OEUFS DJP PLE A,0.835699,500G OIGNON RGE FR,0.580387,BANANE CRF BIO,20 OEUFS DJP PLE A,20X OEUFS DJP SOL CRF CLASSICPaiement en caisse,20 OEUFS DJP PLE A
292,63232835993,2024-07-06,2.91,0.0,20X OEUFS DJP SOL CRF CLASSIC,NaN,0.68,Paiement en caisse,[ 0.01215151 0.03599822 0.00197543 0.027010...,20 OEUFS DJP PLE A,0.835699,ROLL APERO AFH CRF,0.685178,BANANE CRF BIO,20 OEUFS DJP PLE A,20X OEUFS DJP SOL CRF CLASSICPaiement en caisse,20 OEUFS DJP PLE A
313,65151304770,2025-03-22,4.53,0.0,FLT 2KG PDT BLC VAP CRF FR,NaN,0.45,Paiement en caisse,[ 4.21104860e-03 2.07976755e-02 -2.77502406e-...,PDT VAP BLANCHE 2K,0.751452,6X1.5L EAU AUV CRF,0.661127,BANANE CRF BIO,PDT VAP BLANCHE 2K,FLT 2KG PDT BLC VAP CRF FRPaiement en caisse,PDT VAP BLANCHE 2K
316,65151304770,2025-03-22,4.53,0.0,FLT 2KG ORANGE DESSERT CRF HF,NaN,0.52,Paiement en caisse,[ 8.61066859e-03 5.36054671e-02 -7.54230330e-...,ORANGE DESSERT 2KG,0.870981,LOT QUICHE LORRAIN,0.599243,6X1.5L EAU AUV CRF,ORANGE DESSERT 2KG,FLT 2KG ORANGE DESSERT CRF HFPaiement en caisse,ORANGE DESSERT 2KG
323,65146373916,2025-03-15,10.62,0.0,FLT 2KG PDT BLC VAP CRF FR,NaN,0.33,Paiement en caisse,[ 4.21104860e-03 2.07976755e-02 -2.77502406e-...,PDT VAP BLANCHE 2K,0.751452,6X1.5L EAU AUV CRF,0.661127,NaN,PDT VAP BLANCHE 2K,FLT 2KG PDT BLC VAP CRF FRPaiement en caisse,PDT VAP BLANCHE 2K
327,65151220627,2025-03-08,21.30,0.0,FLT 2KG ORANGE DESSERT CRF HF,NaN,0.38,Paiement en caisse,[ 8.61066859e-03 5.36054671e-02 -7.54230330e-...,ORANGE DESSERT 2KG,0.870981,BANANE CRF BIO,0.608361,BANANE CRF BIO,ORANGE DESSERT 2KG,FLT 2KG ORANGE DESSERT CRF HFPaiement en caisse,ORANGE DESSERT 2KG

In [37]:
df_loyalty.query('(matchedLabel1.notna()) and (similarity_score1 > 0.7)').head(30)

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel
0,64070450536,2024-09-28,0.66,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP POULE,0.844788,NaN,NaN,20 OEUFS DJP POULE,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,BQ CROQUE BB FROM,0.623993,BANANE CRF BIO,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.0,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-3.55873778e-02 6.42536953e-02 -1.99550646e-...,1KG COUSCOUS MOYEN,0.899923,CHAUSSONS AUX POMM,0.611897,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Yaourt aux fruits jaunes pêche abricot poire a...,0.619123,Yaourt aux fruits rouges fraise framboise ceri...,Bananes Bio CARREFOUR BIO
5,64068321557,2024-09-13,8.32,0.0,FLT 500G CITRON VERT,NaN,0.60,Paiement en caisse,[-2.83033047e-02 6.72009820e-03 3.18499729e-...,CITRON VERT 500G,0.921041,NaN,NaN,CITRON VERT 500G,CITRON VERT 500G
6,64068321557,2024-09-13,8.32,0.0,1KG FROMAGE FRAIS 0%MG CRF CLA,NaN,0.27,Paiement en caisse,[-7.89078232e-03 4.75184172e-02 2.95940619e-...,1KG FROMAGE FRAIS,0.914593,NaN,NaN,1KG FROMAGE FRAIS,1KG FROMAGE FRAIS
7,64068321557,2024-09-13,8.32,0.0,OIGNON ROUGE BOTTE,NaN,0.40,Paiement en caisse,[-5.34472689e-02 6.90731257e-02 -2.66275071e-...,BOTTE OIGNON ROUGE,0.969702,NaN,NaN,BOTTE OIGNON ROUGE,BOTTE OIGNON ROUGE
8,64068321557,2024-09-13,8.32,0.0,PAIN COMPLET CRF BIO 400G,NaN,0.68,Paiement en caisse,[-6.05254024e-02 1.02311485e-02 -1.37503650e-...,PAIN COMPLET CRF B,0.898617,NaN,NaN,PAIN COMPLET CRF B,PAIN COMPLET CRF B
10,64068321557,2024-09-13,8.32,0.0,"ST 200G HARICOT.MUNGO 0,99",NaN,0.15,Paiement en caisse,[-3.06809694e-02 7.08247721e-02 9.43106040e-...,HARICOT MUNGO,0.867010,NaN,NaN,HARICOT MUNGO,HARICOT MUNGO
11,64068321557,2024-09-13,8.32,0.0,ARTICHAUT PIECE,NaN,0.40,Paiement en caisse,[-2.10595597e-02 8.66309553e-02 -2.59835087e-...,ARTICHAUT,0.911951,NaN,NaN,ARTICHAUT,ARTICHAUT
12,64068321557,2024-09-13,8.32,0.0,FLT ECHALOTE 500G SIMPL FR,NaN,0.29,Paiement en caisse,[ 1.26887113e-02 1.16611840e-02 4.47784504e-...,FLT ECHALOT SIMPL,0.918302,FLT 350G ECHALOTE,0.884147,FLT 350G ECHALOTE,FLT ECHALOT SIMPL
13,64068321557,2024-09-13,8.32,0.0,FILET AIL 3 TETES,NaN,0.60,Paiement en caisse,[-4.22943980e-02 4.50514071e-02 -3.21561955e-...,FILET AIL 3 TETES,1.000000,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES
14,64068321557,2024-09-13,8.32,0.0,16X125G YRT FRUIT 0% CRF CLASS,NaN,0.61,Paiement en caisse,[ 3.58122922e-02 4.65148054e-02 2.72555789e-...,16X125G YRT FRUIT,0.937719,NaN,NaN,16X125G YRT FRUIT,16X125G YRT FRUIT
15,64068321557,2024-09-13,8.32,0.0,RADIS ROSE BOTTE,NaN,0.25,Paiement en caisse,[-0.02848347 0.06624474 -0.009954 -0.039595...,RADIS ROSE BOTTE,1.000001,NaN,NaN,RADIS ROSE BOTTE,RADIS ROSE BOTTE
16,64068321557,2024-09-13,8.32,0.0,FLT 350G ECHALOTE FR,NaN,0.40,Paiement en caisse,[ 1.41091580e-02 3.37692834e-02 1.80433672e-...,FLT 350G ECHALOTE,0.992623,FLT ECHALOT SIMPL,0.836567,FLT 350G ECHALOTE,FLT 350G ECHALOTE
19,64066513404,2024-09-11,14.56,0.0,125G MOZZARELLA VACHE,NaN,1.19,Paiement en caisse,[-5.44288233e-02 5.41778877e-02 7.58662261e-...,FD 125G MOZZARELLA,0.874016,SARDINE ATLANTIQUE,0.602897,FD 125G MOZZARELLA,FD 125G MOZZARELLA
20,64066513404,2024-09-11,14.56,0.0,16X125G BIF NATURE ACTIVIA OD,NaN,1.35,Paiement en caisse,[-1.87312532e-02 3.14560719e-02 -5.82224280e-...,FD 16X125G BIF NAT,0.733277,NaN,NaN,FD 16X125G BIF NAT,FD 16X125G BIF NAT
25,64072492932,2024-09-07,5.20,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.40,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Mouchoirs Confort CARREFOUR SOFT,0.584913,NaN,Bananes Bio CARREFOUR BIO
27,64068320573,2024-09-06,17.03,0.0,2X75ML DENT PSA NETT INTENS OB,NaN,4.70,Paiement en caisse,[-2.34636348e-02 6.90753087e-02 -3.45805325e-...,2X75ML DENT PSA NE,0.941529,2X75ML DENT S.G CA,0.844322,2X75ML DENT PSA NE,2X75ML DENT PSA NE
29,64068320573,2024-09-06,17.03,0.0,2X75ML PSA GENC&EMAIL ORIG OB,NaN,4.24,Paiement en caisse,[-1.09107262e-02 5.68357967e-02 -2.19687540e-...,2X75ML PSA GENC.EM,0.798994,2X75ML DENT PSA NE,0.689010,2X75ML DENT S.G CA,2X75ML PSA GENC.EM
30,64068320573,2024-09-06,17.03,0.0,AG SCOL OXFORD FLOWERS 12X18,NaN,1.40,Paiement en caisse,[-7.52465129e-02 1.05701536e-01 -1.97810344e-...,AG OXFORD FLOWERS,0.930284,20 OEUFS SOL,0.606849,AG OXFORD FLOWERS,AG OXFORD FLOWERS
35,64629132253,2024-10-26,1.93,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.30,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,VELOUTE FRUIX PANA,0.711454,BANANE CRF BIO,BANANE CRF BIO
36,64629132253,2024-10-26,1.93,0.0,500G LUTTI HAPPY FIZZ,NaN,1.63,Paiement en caisse,[-5.88268638e-02 4.12295535e-02 2.24247370e-...,500G LUTTI HAPPY F,0.887900,NaN,NaN,500G LUTTI HAPPY F,500G LUTTI HAPPY F
37,64635897084,2024-10-19,10.50,0.0,SWITCH SET MARIO KART 8 PASS C,NaN,10.50,Paiement en ligne,[-2.60374770e-02 1.16239954e-02 -1.83791779e-...,Jeu Pass Circuits additionnels Mario Kart 8 De...,0.780558,ARTICHAUT,0.556534,Jeu Pass Circuits additionnels Mario Kart 8 De...,Jeu Pass Circuits additionnels Mario Kart 8 De...
38,64625112459,2024-10-19,5.58,0.0,"FLT 1,5KG ORANGE DESSERT CRF",NaN,0.80,Paiement en caisse,[ 2.00817175e-02 5.36383279e-02 -1.25660766e-...,FLT 1.5KG ORANGE,0.889461,KG TOMATE GRAP FR,0.608681,FLT 1.5KG ORANGE,FLT 1.5KG ORANGE
39,64625112459,2024-10-19,5.58,0.0,BQ 200G CHAMPIGNONS BRUN FQC,NaN,0.40,Paiement en caisse,[-5.98149337e-02 7.97882453e-02 -4.72447202e-...,BQ 200G CHAMP FQC,0.950953,PCE BROCOLI FQC F,0.716837,BQ 200G CHAMP FQC,BQ 200G CHAMP FQC
40,64625112459,2024-10-19,5.58,0.0,BROCOLI PCE FR,NaN,0.40,Paiement en caisse,[-8.05055574e-02 2.93795876e-02 -5.18177114e-...,PCE BROCOLI FQC F,0.928941,CROQUE EMMENTAL,0.678980,PCE BROCOLI FQC F,PCE BROCOLI FQC F
42,64625112459,2024-10-19,5.58,0.0,KIWI VERT PIECE,NaN,0.80,Paiement en caisse,[-7.73044601e-02 8.06826279e-02 1.48842391e-...,KIWI VERT PIECE,1.000000,CITRON VERT PIECE,0.714278,KIWI VERT PIECE,KIWI VERT PIECE
43,64625112459,2024-10-19,5.58,0.0,BATAVIA SALADE PIECE,NaN,0.19,Paiement en caisse,[-6.11950867e-02 7.64010102e-02 -6.13852218e-...,BATAVIA PIECE,0.931950,125G MOZZARELLA B,0.611053,AVOCAT PIECE,BATAVIA PIECE
45,64625112459,2024-10-19,5.58,0.0,CITRON VERT PIECE,NaN,0.19,Paiement en caisse,[-3.13694961e-02 3.07015125e-02 1.07522709e-...,CITRON VERT PIECE,1.000000,PIMENT VERT,0.728039,CITRON VERT PIECE,CITRON VERT PIECE

In [23]:
df_loyalty

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,20 OEUFS DJP POULE,0.844788,NaN,NaN,20 OEUFS DJP POULE,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,BQ CROQUE BB FROM,0.623993,BANANE CRF BIO,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,[-3.55873778e-02 6.42536953e-02 -1.99550646e-...,1KG COUSCOUS MOYEN,0.899923,CHAUSSONS AUX POMM,0.611897,1KG COUSCOUS MOYEN,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,Bananes Bio CARREFOUR BIO,0.839969,Yaourt aux fruits jaunes pêche abricot poire a...,0.619123,Yaourt aux fruits rouges fraise framboise ceri...,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,[-6.34368062e-02 7.53262192e-02 -9.41641927e-...,CHOU FLEUR PIECE,1.000000,1L HUILE FLEUR DE,0.695785,CHOU FLEUR PIECE,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,NaN,NaN,BANANE CRF BIO,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_loyalty.query("date == @pd.to_datetime('2024-06-27')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel
223,63089578206,2024-06-27,0.94,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Crêpes jambon emmental CARREFOUR CLASSIC',0.597213,NaN,NaN,Boisson végétale au soja nature Bio CARREFOUR BIO,Crêpes jambon emmental CARREFOUR CLASSIC'
224,63089578206,2024-06-27,0.94,0.0,1L BOISSON SOJA NATUR CARF BIO,NaN,0.48,Paiement en ligne,[-4.70703021e-02 1.43808890e-02 -2.76396256e-...,Boisson végétale au soja nature Bio CARREFOUR BIO,0.863731,Nectar de goyave CARREFOUR SELECTION,0.613106,Boisson végétale au soja nature Bio CARREFOUR BIO,Boisson végétale au soja nature Bio CARREFOUR BIO

In [41]:
df_loyalty.query("date == @pd.to_datetime('2024-08-18')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel
74,63724848170,2024-08-18,4.45,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.80,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,BANANE CRF BIO,0.845570,250G RICOTTA CRF C,0.598712,BANANE CRF BIO,BANANE CRF BIO
75,63724848170,2024-08-18,4.45,0.0,POMELO PIECE,NaN,0.35,Paiement en caisse,[ 1.19124604e-02 3.96920331e-02 -8.59128386e-...,POMELO ROSE PIECE,0.928144,POIVRON ROUGE,0.680349,POMELO ROSE PIECE,POMELO ROSE PIECE
76,63724848170,2024-08-18,4.45,0.0,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.02,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,63724848170,2024-08-18,4.45,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.60,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,250G RICOTTA CRF C,0.598712,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO
78,63724848170,2024-08-18,4.45,0.0,"ST 1,5KG POMME GALA FR",NaN,0.64,Paiement en caisse,[ 1.84565242e-02 1.54451365e-02 -2.40025707e-...,ST GALA FR,0.777189,POMELO ROSE PIECE,0.749137,ST GALA FR,ST GALA FR
79,63724848170,2024-08-18,4.45,0.0,KIWI VERT PIECE,NaN,1.04,Paiement en caisse,[-7.73044601e-02 8.06826279e-02 1.48842391e-...,KIWI VERT PIECE,1.000000,PECHE PLATE VRAC,0.636053,KIWI VERT PIECE,KIWI VERT PIECE

In [25]:
df_prod.query("dateKey == @pd.to_datetime('2024-06-27')")

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalAmountImmediateDiscount,totalPriceAfterDiscount
1579,2024-06-27,order,1,3.174660e+12,3013532.0,Sucre roux pure canne blond BLONVILLIERS,sucre-roux-pure-canne-blond-blonvilliers,food,"Sucres, Farines et Aide à la pâtisserie",NaN,1,0.0,2.85,2.85,NaN,NaN,NaN
1580,2024-06-27,receipt,6,NaN,NaN,SAC CADEAU PETIT 9,SAC CADEAU PETIT 9,other,NaN,20.0,0,0.0,3.60,0.00,0.0,NaN,0.00
1581,2024-06-27,order,1,3.270190e+12,843500.0,Crêpes jambon emmental CARREFOUR CLASSIC',crepes-jambon-emmental-carrefour-classic,food,"Apéritifs, Entrées et Snacking",NaN,1,0.0,3.95,3.95,NaN,NaN,NaN
1582,2024-06-27,order,1,3.100882e+12,6722003.0,Eau gazeuse minérale naturelle ST-YORRE,eau-gazeuse-minerale-naturelle-st-yorre,food,Eaux,NaN,2,0.0,3.96,7.92,NaN,NaN,NaN
1583,2024-06-27,order,1,3.000000e+12,432685.0,Bananes Cavendish vrac,bananes-cavendish-vrac,food,Fruits,NaN,1,0.0,1.99,1.99,NaN,NaN,NaN
1584,2024-06-27,order,1,3.033490e+12,6287309.0,Yaourt nature DANONE,yaourt-nature-danone,food,Yaourts et Fromages blancs,NaN,1,0.0,3.35,3.35,NaN,NaN,NaN
1585,2024-06-27,receipt,1,NaN,NaN,BANANE 5 DOIGTS,BANANE 5 DOIGTS,food,NaN,5.5,1,0.0,0.99,0.99,0.0,NaN,0.99
1586,2024-06-27,order,1,3.033710e+12,46564.0,Carrés de chocolat noir 70% NESTLE LES RECETTE...,carres-de-chocolat-noir-70-nestle-les-recettes...,food,Confiseries et Chocolats,NaN,1,0.0,4.09,4.09,NaN,NaN,NaN
1587,2024-06-27,order,1,3.560071e+12,6557620.0,Œufs frais poules au sol CARREFOUR CLASSIC',oeufs-frais-poules-au-sol-carrefour-classic,food,Œufs,NaN,1,0.0,4.55,4.55,NaN,NaN,NaN
1588,2024-06-27,receipt,4,NaN,NaN,SAC CADEAU BOUTEIL,SAC CADEAU BOUTEIL,other,NaN,20.0,2,0.0,2.99,5.98,0.0,NaN,5.98
1589,2024-06-27,order,1,3.270190e+12,1099221.0,Boisson végétale au soja nature Bio CARREFOUR BIO,boisson-vegetale-au-soja-nature-bio-carrefour-bio,food,Bio à Petit prix,NaN,4,0.0,1.19,4.76,NaN,NaN,NaN
1590,2024-06-27,order,1,7.613036e+12,6397521.0,Eau minérale naturelle VITTEL,eau-minerale-naturelle-vittel,food,Eaux,NaN,6,0.0,2.94,17.64,NaN,NaN,NaN
1591,2024-06-27,order,1,3.033710e+12,135237.0,Arome MAGGI,arome-maggi,food,Ingrédients pour cuisiner,NaN,1,0.0,7.49,7.49,NaN,NaN,NaN
1592,2024-06-27,order,1,3.245413e+12,2931986.0,Colin d'Alaska à la bordelaise CARREFOUR,colin-d-alaska-a-la-bordelaise-carrefour,food,Poissons et Fruits de mer,NaN,0,0.0,3.09,0.00,NaN,NaN,NaN
1593,2024-06-27,order,1,3.033492e+12,6945178.0,Yaourt aux fruits brassé fraise framboise pêch...,yaourt-aux-fruits-brasse-fraise-framboise-pech...,food,Yaourts et Fromages blancs,NaN,1,0.0,4.59,4.59,NaN,NaN,NaN
1594,2024-06-27,order,1,9.713236e+12,7537445.0,Sacs réutilisables consignés,sacs-reutilisables-consignes,other,RETURNABLE_BAG,NaN,0,0.0,0.35,0.00,NaN,NaN,NaN
1595,2024-06-27,order,1,3.560070e+12,3635056.0,Nectar de goyave CARREFOUR SELECTION,nectar-de-goyave-carrefour-selection,food,Jus de fruits et légumes,NaN,2,0.0,2.25,4.50,NaN,NaN,NaN
1596,2024-06-27,order,1,3.245414e+12,3476365.0,Colin d'Alaska à la parisienne CARREFOUR,colin-d-alaska-a-la-parisienne-carrefour,food,Poissons et Fruits de mer,NaN,0,0.0,2.99,0.00,NaN,NaN,NaN
1597,2024-06-27,order,1,3.245413e+12,2810657.0,Huile de pépins de raisin CARREFOUR CLASSIC',huile-de-pepins-de-raisin-carrefour-classic,food,"Huiles, Vinaigres et Vinaigrettes",NaN,1,0.0,5.45,5.45,NaN,NaN,NaN
1598,2024-06-27,receipt,4,NaN,NaN,SAC CADEAU MOYEN,SAC CADEAU MOYEN,other,NaN,20.0,0,0.0,3.99,0.00,0.0,NaN,0.00

In [26]:
df_loyalty.query("date == @pd.to_datetime('2024-10-19')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel
37,64635897084,2024-10-19,10.50,0.0,SWITCH SET MARIO KART 8 PASS C,NaN,10.50,Paiement en ligne,[-2.60374770e-02 1.16239954e-02 -1.83791779e-...,Jeu Pass Circuits additionnels Mario Kart 8 De...,0.780558,ARTICHAUT,0.556534,Jeu Pass Circuits additionnels Mario Kart 8 De...,Jeu Pass Circuits additionnels Mario Kart 8 De...
38,64625112459,2024-10-19,5.58,0.0,"FLT 1,5KG ORANGE DESSERT CRF",NaN,0.80,Paiement en caisse,[ 2.00817175e-02 5.36383279e-02 -1.25660766e-...,FLT 1.5KG ORANGE,0.889461,KG TOMATE GRAP FR,0.608681,FLT 1.5KG ORANGE,FLT 1.5KG ORANGE
39,64625112459,2024-10-19,5.58,0.0,BQ 200G CHAMPIGNONS BRUN FQC,NaN,0.40,Paiement en caisse,[-5.98149337e-02 7.97882453e-02 -4.72447202e-...,BQ 200G CHAMP FQC,0.950953,PCE BROCOLI FQC F,0.716837,BQ 200G CHAMP FQC,BQ 200G CHAMP FQC
40,64625112459,2024-10-19,5.58,0.0,BROCOLI PCE FR,NaN,0.40,Paiement en caisse,[-8.05055574e-02 2.93795876e-02 -5.18177114e-...,PCE BROCOLI FQC F,0.928941,CROQUE EMMENTAL,0.678980,PCE BROCOLI FQC F,PCE BROCOLI FQC F
41,64625112459,2024-10-19,5.58,0.0,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.10,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,64625112459,2024-10-19,5.58,0.0,KIWI VERT PIECE,NaN,0.80,Paiement en caisse,[-7.73044601e-02 8.06826279e-02 1.48842391e-...,KIWI VERT PIECE,1.000000,CITRON VERT PIECE,0.714278,KIWI VERT PIECE,KIWI VERT PIECE
43,64625112459,2024-10-19,5.58,0.0,BATAVIA SALADE PIECE,NaN,0.19,Paiement en caisse,[-6.11950867e-02 7.64010102e-02 -6.13852218e-...,BATAVIA PIECE,0.931950,125G MOZZARELLA B,0.611053,AVOCAT PIECE,BATAVIA PIECE
44,64625112459,2024-10-19,5.58,0.0,BQ250G TT CERISE ALL SIMPL HF,NaN,0.60,Paiement en caisse,[-3.69635709e-02 5.96843250e-02 1.45964893e-...,NaN,NaN,BQ 200G CHAMP FQC,0.704524,BQ TOM CERISE ALL,NaN
45,64625112459,2024-10-19,5.58,0.0,CITRON VERT PIECE,NaN,0.19,Paiement en caisse,[-3.13694961e-02 3.07015125e-02 1.07522709e-...,CITRON VERT PIECE,1.000000,PIMENT VERT,0.728039,CITRON VERT PIECE,CITRON VERT PIECE
46,64625112459,2024-10-19,5.58,0.0,AVOCAT PIECE,NaN,0.50,Paiement en caisse,[-4.77894507e-02 5.91016859e-02 -4.03642952e-...,AVOCAT PIECE,1.000000,KIWI VERT PIECE,0.677243,AVOCAT PIECE,AVOCAT PIECE
47,64625112459,2024-10-19,5.58,0.0,ARTICHAUT PIECE,NaN,0.60,Paiement en caisse,[-2.10595597e-02 8.66309553e-02 -2.59835087e-...,ARTICHAUT,0.911951,AVOCAT PIECE,0.750778,ARTICHAUT,ARTICHAUT

In [60]:
df_loyalty.query("date == @pd.to_datetime('2024-09-06')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
27,64068320573,2024-09-06,17.03,0.0,2X75ML DENT PSA NETT INTENS OB,NaN,4.70,Paiement en caisse,[-2.34636348e-02 6.90753087e-02 -3.45805325e-...,2X75ML DENT PSA NE,0.941529,2X75ML DENT S.G CA,0.844322,2X75ML DENT PSA NE,2X75ML DENT PSA NE,2X75ML DENT PSA NETT INTENS OBPaiement en caisse,NaN
28,64068320573,2024-09-06,17.03,0.0,NaN,"Pour l achat de 1 produit(s),",0.78,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,64068320573,2024-09-06,17.03,0.0,2X75ML PSA GENC&EMAIL ORIG OB,NaN,4.24,Paiement en caisse,[-1.09107262e-02 5.68357967e-02 -2.19687540e-...,2X75ML PSA GENC.EM,0.798994,20 OEUFS SOL,0.634638,2X75ML DENT S.G CA,2X75ML PSA GENC.EM,2X75ML PSA GENC&EMAIL ORIG OBPaiement en caisse,NaN
30,64068320573,2024-09-06,17.03,0.0,AG SCOL OXFORD FLOWERS 12X18,NaN,1.40,Paiement en caisse,[-7.52465129e-02 1.05701536e-01 -1.97810344e-...,AG OXFORD FLOWERS,0.930284,USH DCH ORCHIDEE B,0.602687,AG OXFORD FLOWERS,AG OXFORD FLOWERS,AG SCOL OXFORD FLOWERS 12X18Paiement en caisse,NaN
31,64068320573,2024-09-06,17.03,0.0,NaN,"Pour l achat de 1 produit(s),",1.66,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,64068320573,2024-09-06,17.03,0.0,2X75ML DENT S&G CALM ORIGIN OB,NaN,4.25,Paiement en caisse,[-4.17402722e-02 7.24742711e-02 1.11273574e-...,2X75ML DENT S.G CA,0.749601,2X75ML DENT PSA NE,0.682258,2X75ML DENT S.G CA,2X75ML DENT S.G CA,2X75ML DENT S&G CALM ORIGIN OBPaiement en caisse,NaN

In [59]:
df_loyalty.query('(matchedLabel1 != matchedLabelFuzzy) and (matchedLabel1.notna()) and (similarity_score1 < 0.7) and (matchedLabelFuzzy.notna())').tail(30)

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabel2,similarity_score2,matchedLabelFuzzy,matchedLabel,itemLabelOperation,mostFrequentMatchedLabel1
72,63726335992,2024-08-26,0.82,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Œufs frais poules au sol CARREFOUR CLASSIC',0.588981,Huile de pépins de raisin CARREFOUR CLASSIC',0.574062,Boisson végétale au soja nature Bio CARREFOUR...,Œufs frais poules au sol CARREFOUR CLASSIC',20 OEUFS DJP POULE AU SOL CRFPaiement en ligne,Œufs frais poules au sol CARREFOUR CLASSIC'
77,63724848170,2024-08-18,4.45,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.60,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,250G RICOTTA CRF C,0.598712,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
84,63726339040,2024-08-09,1.74,0.0,MAIS SANS SUCRE AJOUTE BOITE 3,NaN,0.54,Paiement en ligne,[-3.60063277e-02 2.51771137e-02 -7.07581788e-...,Maïs sans sucres ajoutés CARREFOUR CLASSIC',0.596173,Maïs sans sucres ajoutés CARREFOUR CLASSIC',0.596173,Pain de mie American sandwich complet sans suc...,Maïs sans sucres ajoutés CARREFOUR CLASSIC',MAIS SANS SUCRE AJOUTE BOITE 3Paiement en ligne,NaN
97,65144522536,2024-12-20,3.43,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.30,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,KG TOMATE GRAP FR,0.573115,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO
205,63089401410,2024-05-24,4.56,0.0,1X8L FF BP MATIN LEGER ECREME,NaN,4.08,Paiement en ligne,[-2.06623878e-02 5.01386821e-02 -4.18329276e-...,PANIER LEGUMES X1,0.639516,3X150G LT3 DELIC L,0.624134,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,Lait Sans lactose UHT Ecrémé Matin Léger LACTEL,1X8L FF BP MATIN LEGER ECREMEPaiement en ligne,NaN
223,63089578206,2024-06-27,0.94,0.0,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en ligne,[-4.58448101e-03 4.76486869e-02 -5.69319613e-...,Crêpes jambon emmental CARREFOUR CLASSIC',0.597213,Œufs frais poules au sol CARREFOUR CLASSIC',0.588981,Boisson végétale au soja nature Bio CARREFOUR BIO,Œufs frais poules au sol CARREFOUR CLASSIC',20 OEUFS DJP POULE AU SOL CRFPaiement en ligne,Œufs frais poules au sol CARREFOUR CLASSIC'
285,63234561756,2024-07-26,9.24,0.0,BANANE CRF BIO MH 5 FRUITS,NaN,0.39,Paiement en caisse,[ 2.37073675e-02 1.58613566e-02 -5.29897586e-...,POMME GRANNY VRAC,0.609958,BANANE CRF BIO,0.845570,BANANE CRF BIO,BANANE CRF BIO,BANANE CRF BIO MH 5 FRUITSPaiement en caisse,BANANE CRF BIO

In [62]:
df_prod = pd.merge(
    df_prod,
    df_loyalty_amounts,
    how="left",
    left_on=["dateKey", "productLabel"],
    right_on=["date", "matchedLabel"],
    suffixes=("", "_loyalty"),
)

In [63]:
df_prod.query('productLabel.str.contains("SAUMON", case=False)')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory,vatPercentage,...,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalAmountImmediateDiscount,totalPriceAfterDiscount,date,itemLabel,itemRd,matchedLabel
144,2025-05-03,receipt,1,NaN,NaN,PAVE SAUMON,PAVE SAUMON,food,NaN,5.5,...,1.116,19.99,22.31,0.00,NaN,22.31,NaT,NaN,NaN,NaN
352,2025-03-29,receipt,2,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,3.300,18.99,62.66,0.00,NaN,62.66,NaT,NaN,NaN,NaN
421,2025-03-08,receipt,2,NaN,NaN,PAVE SAUMON,PAVE SAUMON,food,NaN,5.5,...,1.854,19.99,37.06,-0.30,NaN,36.76,NaT,NaN,NaN,NaN
710,2024-12-27,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.913,8.90,25.93,0.00,NaN,25.93,NaT,NaN,NaN,NaN
771,2024-12-15,receipt,2,NaN,NaN,420G PIZZA SAUMON,420G PIZZA SAUMON,food,NaN,5.5,...,0.000,2.25,4.50,-0.68,NaN,3.82,NaT,NaN,NaN,NaN
875,2024-11-19,receipt,2,NaN,NaN,TARTE SAUMON POIR.,TARTE SAUMON POIR.,food,NaN,5.5,...,0.000,3.89,7.78,-2.33,NaN,5.45,NaT,NaN,NaN,NaN
877,2024-11-19,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,1.998,9.99,19.96,0.00,NaN,19.96,NaT,NaN,NaN,NaN
1178,2024-09-11,receipt,2,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,5.268,11.99,63.17,0.00,NaN,63.17,NaT,NaN,NaN,NaN
2022,2024-03-23,receipt,2,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,4.904,11.99,58.80,0.00,NaN,58.80,NaT,NaN,NaN,NaN
2710,2023-11-24,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.808,9.99,28.05,0.00,NaN,28.05,NaT,NaN,NaN,NaN
2990,2023-09-19,receipt,1,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,2.430,9.99,24.28,0.00,NaN,24.28,NaT,NaN,NaN,NaN
3016,2023-09-15,receipt,1,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,2.218,12.99,28.81,0.00,NaN,28.81,NaT,NaN,NaN,NaN
3204,2023-08-11,receipt,2,NaN,NaN,SAUMON ENTIER,SAUMON ENTIER,food,NaN,5.5,...,5.700,9.99,56.94,0.00,NaN,56.94,NaT,NaN,NaN,NaN
3238,2023-08-04,receipt,1,NaN,NaN,FILET SAUMON FQC A,FILET SAUMON FQC A,food,NaN,5.5,...,2.310,13.99,32.32,0.00,NaN,32.32,NaT,NaN,NaN,NaN
4122,2022-12-31,receipt,1,NaN,NaN,PAVE SAUMON,PAVE SAUMON,food,NaN,5.5,...,0.000,15.00,15.00,0.00,NaN,15.00,NaT,NaN,NaN,NaN
4912,2022-06-29,receipt,1,NaN,NaN,SAUMON SCE OSEILLE,SAUMON SCE OSEILLE,food,NaN,5.5,...,0.000,4.95,4.95,0.00,NaN,4.95,NaT,NaN,NaN,NaN

In order to merge loyalty data that is not specific to one product one should also examine the category of the item.

In [ ]:
grouped_rayon = df_loyalty_amounts.query("(itemLabel.notna()) & (itemLabel.str.contains('ART RAYON'))").groupby(['date','itemLabel']).agg(
    {
        'itemRd': 'sum',
    }
).reset_index()

In [ ]:
grouped_rayon

         date                       itemLabel  itemRd
0  2024-05-17    ART RAYON FRUITS LEG TVA 5,5    0.47
1  2024-07-26    ART RAYON FRUITS LEG TVA 5,5    2.94
2  2024-08-18    ART RAYON FRUITS LEG TVA 5,5    1.02
3  2024-08-30  ART RAYON POISSONNERIE TVA 5,5    2.46
4  2024-09-11  ART RAYON POISSONNERIE TVA 5,5    9.48
5  2024-09-13    ART RAYON FRUITS LEG TVA 5,5    3.67
6  2024-10-01  ART RAYON POISSONNERIE TVA 5,5    0.88
7  2024-10-19    ART RAYON FRUITS LEG TVA 5,5    1.10
8  2024-11-19  ART RAYON POISSONNERIE TVA 5,5    2.99
9  2024-12-20    ART RAYON FRUITS LEG TVA 5,5    0.64
10 2024-12-31     ART RAYON BOUCHERIE TVA 5,5    2.90
11 2025-01-14    ART RAYON FRUITS LEG TVA 5,5    0.42
12 2025-01-21     ART RAYON BOUCHERIE TVA 5,5    2.43
13 2025-01-21    ART RAYON FRUITS LEG TVA 5,5    1.56
14 2025-01-28    ART RAYON FRUITS LEG TVA 5,5    2.17
15 2025-02-01    ART RAYON FRUITS LEG TVA 5,5    0.38
16 2025-02-06    ART RAYON FRUITS LEG TVA 5,5    0.99
17 2025-02-16    ART RAYON FRUITS LEG TVA 5,5    0.52
18 2025-02-22    ART RAYON FRUITS LEG TVA 5,5    1.11
19 2025-02-28    ART RAYON FRUITS LEG TVA 5,5    2.49
20 2025-03-08    ART RAYON FRUITS LEG TVA 5,5    1.29
21 2025-03-08  ART RAYON POISSONNERIE TVA 5,5   18.42
22 2025-03-15     ART RAYON BOUCHERIE TVA 5,5    6.60
23 2025-03-22    ART RAYON FRUITS LEG TVA 5,5    1.16
24 2025-03-29    ART RAYON FRUITS LEG TVA 5,5    3.08
25 2025-03-29  ART RAYON POISSONNERIE TVA 5,5   15.67
26 2025-04-05     ART RAYON BOUCHERIE TVA 5,5    7.77
27 2025-04-05    ART RAYON FRUITS LEG TVA 5,5    1.48
28 2025-04-12    ART RAYON FRUITS LEG TVA 5,5    3.27
29 2025-04-17    ART RAYON FRUITS LEG TVA 5,5    1.58
30 2025-04-25    ART RAYON FRUITS LEG TVA 5,5    1.36
31 2025-04-29    ART RAYON FRUITS LEG TVA 5,5    1.34

In [ ]:
groupedByDate_rayon = pd.pivot_table(
    grouped_rayon,
    index="date",
    columns="itemLabel",
    values="itemRd",
    aggfunc="sum",
    fill_value=0,
).reset_index()

In [ ]:
groupedByDate_rayon

itemLabel,date,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5"
0,2024-05-17,0.00,0.47,0.00
1,2024-07-26,0.00,2.94,0.00
2,2024-08-18,0.00,1.02,0.00
3,2024-08-30,0.00,0.00,2.46
4,2024-09-11,0.00,0.00,9.48
5,2024-09-13,0.00,3.67,0.00
6,2024-10-01,0.00,0.00,0.88
7,2024-10-19,0.00,1.10,0.00
8,2024-11-19,0.00,0.00,2.99
9,2024-12-20,0.00,0.64,0.00
10,2024-12-31,2.90,0.00,0.00
11,2025-01-14,0.00,0.42,0.00
12,2025-01-21,2.43,1.56,0.00
13,2025-01-28,0.00,2.17,0.00
14,2025-02-01,0.00,0.38,0.00
15,2025-02-06,0.00,0.99,0.00
16,2025-02-16,0.00,0.52,0.00
17,2025-02-22,0.00,1.11,0.00
18,2025-02-28,0.00,2.49,0.00
19,2025-03-08,0.00,1.29,18.42
20,2025-03-15,6.60,0.00,0.00
21,2025-03-22,0.00,1.16,0.00
22,2025-03-29,0.00,3.08,15.67
23,2025-04-05,7.77,1.48,0.00
24,2025-04-12,0.00,3.27,0.00
25,2025-04-17,0.00,1.58,0.00
26,2025-04-25,0.00,1.36,0.00
27,2025-04-29,0.00,1.34,0.00

In [ ]:
df_prod = pd.merge(df_prod, groupedByDate_rayon, how='left', left_on='dateKey', right_on='date', suffixes=('', '_loyalty_rayon'))

In [ ]:
df_prod.head(30)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,totalPriceAfterDiscount,subCategory_imputed,date,itemLabel,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5"
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,...,3.35,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,...,12.43,Volaille et Rôtisserie,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,...,5.39,NaN,2025-04-29,750G OMEGA 3 DX ST HUBERT,1.62,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,...,4.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,...,2.45,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,NaN,5.5,...,5.86,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
6,2025-04-29,receipt,2,NaN,NaN,375G PIZZA BOLOGN.,375G PIZZA BOLOGN.,food,NaN,5.5,...,4.14,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
7,2025-04-29,receipt,2,NaN,NaN,410G PIZZA 3 VIAND,410G PIZZA 3 VIAND,food,NaN,5.5,...,4.72,"Pizzas, Quiches et Tartes",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,NaN,5.5,...,1.13,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
9,2025-04-29,receipt,1,NaN,NaN,20 OEUFS SOL,20 OEUFS SOL,food,NaN,5.5,...,5.09,Œufs,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
10,2025-04-29,receipt,2,NaN,NaN,400G COLIN FISH.CH,400G COLIN FISH.CH,food,NaN,5.5,...,6.20,Poissons et Fruits de mer,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
11,2025-04-29,receipt,4,NaN,NaN,BT 3X110MOUCH.CONF,BT 3X110MOUCH.CONF,other,NaN,20.0,...,12.41,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
12,2025-04-29,receipt,1,NaN,NaN,COCA-COLASSSCMINIC,COCA-COLASSSCMINIC,food,NaN,5.5,...,3.65,"Colas, Thés glacés, Sirops et Sodas",NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,NaN,5.5,...,0.69,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
14,2025-04-29,receipt,6,NaN,NaN,OY 1KG SPAGHETTI N,OY 1KG SPAGHETTI N,food,NaN,5.5,...,11.40,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
15,2025-04-29,receipt,2,NaN,NaN,12 RLX P.HYG.3P RO,12 RLX P.HYG.3P RO,other,NaN,20.0,...,7.80,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,NaN,5.5,...,1.24,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
17,2025-04-29,receipt,1,NaN,NaN,132G SABLE CITRON,132G SABLE CITRON,food,NaN,5.5,...,2.49,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
18,2025-04-29,receipt,1,NaN,NaN,200G LARDONS F +30,200G LARDONS F +30,food,NaN,5.5,...,1.99,Charcuterie,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
19,2025-04-29,receipt,1,NaN,NaN,150G GATEAU FOURRE,150G GATEAU FOURRE,food,NaN,5.5,...,3.95,Gâteaux moelleux,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
20,2025-04-29,receipt,1,NaN,NaN,BARRE MINCEUR CERE,BARRE MINCEUR CERE,food,NaN,5.5,...,8.99,NaN,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,NaN,5.5,...,1.98,Légumes,NaT,NaN,NaN,NaN,2025-04-29,0.0,1.34,0.0
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,NaN,5.5,...,2.59,Fruits,2025-04-25,MELON MOYEN PIECE,0.39,MELON MOYEN,2025-04-25,0.0,1.36,0.0
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,NaN,5.5,...,2.99,Légumes,2025-04-25,MCH 500G OIGNON ROUGE FQC FR,0.45,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,NaN,5.5,...,3.19,Légumes,2025-04-25,FILET AIL 3 TETES,0.47,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,NaN,5.5,...,2.49,Légumes,2025-04-25,FLT 350G ECHALOTE FQC FR,0.38,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,NaN,5.5,...,1.01,Légumes,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
27,2025-04-25,receipt,1,NaN,NaN,8X125G LAUTHENTIQ,8X125G LAUTHENTIQ,food,NaN,5.5,...,14.19,Viandes,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
28,2025-04-25,receipt,1,NaN,NaN,PAVE LE PAIN RUST,PAVE LE PAIN RUST,food,NaN,5.5,...,2.05,Pains frais,NaT,NaN,NaN,NaN,2025-04-25,0.0,1.36,0.0
29,2025-04-25,receipt,1,NaN,NaN,FLT 2KG PDT CQLP,FLT 2KG PDT CQLP,food,NaN,5.5,...,3.07,Légumes,2025-04-25,FLT 2KG PDT VP BL CQLP FR,0.46,FLT 2KG PDT CQLP,2025-04-25,0.0,1.36,0.0

In [ ]:
subcategories_matching = {
    "ART RAYON FRUITS LEG TVA 5,5": ["Fruits", "Légumes"],
    "ART RAYON POISSONNERIE TVA 5,5": ["Poissonnerie"],
    "ART RAYON BOUCHERIE TVA 5,5": ["Boucherie"],
    "ART RAYON CHARCUTERIE TVA 5,5": ["Charcuterie"],
}

In [ ]:
df_prod["subCategory_imputed"] = df_prod["subCategory_imputed"].fillna("")
df_prod["subCategory_original"] = df_prod["subCategory_original"].fillna("")
df_prod["itemRd"] = df_prod["itemRd"].fillna(0)

In [ ]:
# Step 1: Filter the DataFrame based on the conditions
# filtered_df = df_prod[
#     (df_prod["itemLabel_loyalty_rayon"].notna()) &
#     (df_prod.apply(
#         lambda row: any(
#             row["subCategory_imputed"] in subcat 
#             for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
#             if row["subCategory_imputed"]
#         ) | any(
#             row["subCategory_original"] in subcat 
#             for subcat in subcategories_matching.get(row["itemLabel_loyalty_rayon"], [])
#             if row["subCategory_original"]
#         ),
#         axis=1
#     ))
# ]

# Step 2: Group by date and calculate the sum of "totalPriceAfterDiscount"
for subitem, categories in subcategories_matching.items():
    # Step 1: Filter the DataFrame based on the conditions
    filtered_df = df_prod[
        (df_prod.apply(
            lambda row: any(
                row["subCategory_imputed"] in subcat 
                for subcat in categories
                if row["subCategory_imputed"]
            ) | any(
                row["subCategory_original"] in subcat 
                for subcat in categories
                if row["subCategory_original"]
            ),
            axis=1)
        ) &
        (df_prod["itemRd"] == 0)
    ]
    df_prod[f"totalPrice_{subitem}"] = (
        filtered_df.groupby(filtered_df["dateKey"].dt.date)["totalPriceAfterDiscount"]
    ).transform("sum")

In [ ]:
df_prod[df_prod["totalPrice_ART RAYON FRUITS LEG TVA 5,5"].notna()].head(30)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5"
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,,5.5,...,0.0,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
34,2025-04-25,receipt,1,NaN,NaN,POIVRON JAUNE,POIVRON JAUNE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
37,2025-04-25,receipt,1,NaN,NaN,POMME GRANNY GROSS,POMME GRANNY GROSS,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
41,2025-04-25,receipt,1,NaN,NaN,MENTHE,MENTHE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
46,2025-04-25,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
48,2025-04-25,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN
57,2025-04-17,receipt,1,NaN,NaN,PATATE DOUCE VRAC,PATATE DOUCE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
58,2025-04-17,receipt,1,NaN,NaN,POMME TERRE STD,POMME TERRE STD,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
60,2025-04-17,receipt,2,NaN,NaN,250GR NOIX FRANC,250GR NOIX FRANC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
76,2025-04-17,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
78,2025-04-17,receipt,1,NaN,NaN,PIMENT VERT,PIMENT VERT,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
97,2025-04-17,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
99,2025-04-17,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-17,0.0,1.58,0.0,12.40,NaN,NaN,NaN
106,2025-04-12,receipt,1,NaN,NaN,CELERI BRANCHE,CELERI BRANCHE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
108,2025-04-12,receipt,1,NaN,NaN,POMME GOLDEN FQC,POMME GOLDEN FQC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
111,2025-04-12,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
114,2025-04-12,receipt,1,NaN,NaN,COURGETTE RONDE,COURGETTE RONDE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
117,2025-04-12,receipt,1,NaN,NaN,ST EPINARD A CUIRE,ST EPINARD A CUIRE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
119,2025-04-12,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
122,2025-04-12,receipt,1,NaN,NaN,POMME TERRE STD,POMME TERRE STD,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
123,2025-04-12,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
125,2025-04-12,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
126,2025-04-12,receipt,1,NaN,NaN,POIREAU VRAC,POIREAU VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
127,2025-04-12,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN
128,2025-04-12,receipt,1,NaN,NaN,BROCOLI VRAC,BROCOLI VRAC,food,,5.5,...,0.0,NaN,2025-04-12,0.0,3.27,0.0,25.00,NaN,NaN,NaN

In [ ]:
df_prod.query('itemRd.notna()')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,itemRd,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5"
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,1.62,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,,5.5,...,0.39,MELON MOYEN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,,5.5,...,0.45,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,,5.5,...,0.47,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,,5.5,...,0.38,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1618,2024-05-17,receipt,1,NaN,NaN,KIWI VERT PIECE,KIWI VERT PIECE,food,,5.5,...,0.48,KIWI VERT PIECE,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1624,2024-05-17,receipt,1,NaN,NaN,PCE CHOU BROCOLIS,PCE CHOU BROCOLIS,food,,5.5,...,0.25,PCE CHOU BROCOLIS,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1625,2024-05-17,receipt,1,NaN,NaN,BETTERAVE FQC,BETTERAVE FQC,food,,5.5,...,0.25,BETTERAVE FQC,2024-05-17,0.0,0.47,0.0,NaN,NaN,NaN,NaN
1647,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,,5.5,...,0.13,1KG FARINE BLE T45,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1648,2024-05-10,receipt,1,NaN,NaN,1KG FARINE BLE T45,1KG FARINE BLE T45,food,,5.5,...,0.13,1KG FARINE BLE T45,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_prod.query("dateKey == @pd.to_datetime('2025-04-25')")[["dateKey", "productLabel", "subCategory_imputed", "totalPriceAfterDiscount", "itemRd", "ART RAYON FRUITS LEG TVA 5,5", "totalPrice_ART RAYON FRUITS LEG TVA 5,5"]].head(30)

,dateKey,productLabel,subCategory_imputed,totalPriceAfterDiscount,itemRd,"ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5"
22,2025-04-25,MELON MOYEN,Fruits,2.59,0.39,1.36,NaN
23,2025-04-25,MCH 500G OIGNON RO,Légumes,2.99,0.45,1.36,NaN
24,2025-04-25,FILET AIL 3 TETES,Légumes,3.19,0.47,1.36,NaN
25,2025-04-25,FLT 350G ECHALOTE,Légumes,2.49,0.38,1.36,NaN
26,2025-04-25,COURGETTE,Légumes,1.01,0.00,1.36,9.38
27,2025-04-25,8X125G LAUTHENTIQ,Viandes,14.19,0.00,1.36,NaN
28,2025-04-25,PAVE LE PAIN RUST,Pains frais,2.05,0.00,1.36,NaN
29,2025-04-25,FLT 2KG PDT CQLP,Légumes,3.07,0.46,1.36,NaN
30,2025-04-25,16X125 NATUR DANON,Yaourts et Fromages blancs,3.35,0.00,1.36,NaN
31,2025-04-25,320G JB SP DD SSOG,,4.75,0.00,1.36,NaN
32,2025-04-25,CELERI BRANCHE,Légumes,0.72,0.14,1.36,NaN
33,2025-04-25,BANANE CRF BIO,Fruits,1.99,0.30,1.36,NaN
34,2025-04-25,POIVRON JAUNE,Légumes,2.23,0.00,1.36,9.38
35,2025-04-25,850G SKYR NATURE Y,Yaourts et Fromages blancs,3.39,0.00,1.36,NaN
36,2025-04-25,125GX16 PAN0% PAN,Yaourts et Fromages blancs,4.59,0.00,1.36,NaN
37,2025-04-25,POMME GRANNY GROSS,Fruits,2.64,0.00,1.36,9.38
38,2025-04-25,BRANDADE MORUE,Poissonnerie,8.89,0.00,1.36,NaN
39,2025-04-25,BATAVIA PIECE,Légumes,1.29,0.20,1.36,NaN
40,2025-04-25,AVOCAT PIECE,Légumes,2.78,0.41,1.36,NaN
41,2025-04-25,MENTHE,Légumes,0.99,0.00,1.36,9.38
42,2025-04-25,ORANGE DESSERT 2KG,Fruits,3.49,0.52,1.36,NaN
43,2025-04-25,PAIN CHOC PB X5 +,,4.99,0.00,1.36,NaN
44,2025-04-25,KIWI VERT PIECE,Fruits,5.52,0.83,1.36,NaN
45,2025-04-25,CHOU FLEUR PIECE,Légumes,2.49,0.38,1.36,NaN
46,2025-04-25,POIRE CONFERENCE,Fruits,1.63,0.00,1.36,9.38
47,2025-04-25,CONCOMBRE PIECE,Légumes,1.29,0.20,1.36,NaN
48,2025-04-25,CAROTTE VRAC,Légumes,0.88,0.00,1.36,9.38
49,2025-04-25,1L HUILE FLEUR DE,"Huiles, Vinaigres et Vinaigrettes",2.95,0.00,1.36,NaN

In [ ]:
# Define the mask for filtering rows
mask = (
    df_prod.apply(
        lambda row: (
            any(
                row["subCategory_imputed"] in subcat_list
                for subcat_list in subcategories_matching.values()
            )
            | any(
                row["subCategory_original"] in subcat_list
                for subcat_list in subcategories_matching.values()
            )
        ),
        axis=1,
    )
    & (df_prod["itemRd"] == 0)
)

# Ensure the required columns exist in df_prod
price_columns = [f"totalPrice_{key}" for key in subcategories_matching.keys() if f"totalPrice_{key}" in df_prod.columns]
amount_columns = [key for key in subcategories_matching.keys() if key in df_prod.columns]

if not price_columns or not amount_columns:
    raise ValueError("Required columns are missing in df_prod.")

# Compute the deferred amount for rows matching the mask
df_prod.loc[mask, "amountRayonDeferred"] = (
    df_prod.loc[mask, "totalPriceAfterDiscount"]
    / df_prod.loc[mask, price_columns].sum(axis=1).replace(0, 1)  # Avoid division by zero
    * df_prod.loc[mask, amount_columns].sum(axis=1)
)

In [ ]:
df_prod.head(50)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,matchedLabel,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,750G OMEGA 3 DX SH,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
5,2025-04-29,receipt,1,NaN,NaN,KG TOMATE GRAP FR,KG TOMATE GRAP FR,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.720404
6,2025-04-29,receipt,2,NaN,NaN,375G PIZZA BOLOGN.,375G PIZZA BOLOGN.,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
7,2025-04-29,receipt,2,NaN,NaN,410G PIZZA 3 VIAND,410G PIZZA 3 VIAND,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
8,2025-04-29,receipt,1,NaN,NaN,AUBERGINE VRAC,AUBERGINE VRAC,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.138917
9,2025-04-29,receipt,1,NaN,NaN,20 OEUFS SOL,20 OEUFS SOL,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
10,2025-04-29,receipt,2,NaN,NaN,400G COLIN FISH.CH,400G COLIN FISH.CH,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
11,2025-04-29,receipt,4,NaN,NaN,BT 3X110MOUCH.CONF,BT 3X110MOUCH.CONF,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
12,2025-04-29,receipt,1,NaN,NaN,COCA-COLASSSCMINIC,COCA-COLASSSCMINIC,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
13,2025-04-29,receipt,1,NaN,NaN,POIVRON ROUGE,POIVRON ROUGE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.084826
14,2025-04-29,receipt,6,NaN,NaN,OY 1KG SPAGHETTI N,OY 1KG SPAGHETTI N,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
15,2025-04-29,receipt,2,NaN,NaN,12 RLX P.HYG.3P RO,12 RLX P.HYG.3P RO,other,,20.0,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
16,2025-04-29,receipt,1,NaN,NaN,HARICOT VERT FIN,HARICOT VERT FIN,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.152440
17,2025-04-29,receipt,1,NaN,NaN,132G SABLE CITRON,132G SABLE CITRON,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
18,2025-04-29,receipt,1,NaN,NaN,200G LARDONS F +30,200G LARDONS F +30,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,1.99,1.340000
19,2025-04-29,receipt,1,NaN,NaN,150G GATEAU FOURRE,150G GATEAU FOURRE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
20,2025-04-29,receipt,1,NaN,NaN,BARRE MINCEUR CERE,BARRE MINCEUR CERE,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,NaN
21,2025-04-29,receipt,2,NaN,NaN,BQ TOM CERISE ALL,BQ TOM CERISE ALL,food,,5.5,...,NaN,2025-04-29,0.0,1.34,0.0,10.90,NaN,NaN,NaN,0.243413
22,2025-04-25,receipt,1,NaN,NaN,MELON MOYEN,MELON MOYEN,food,,5.5,...,MELON MOYEN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
23,2025-04-25,receipt,1,NaN,NaN,MCH 500G OIGNON RO,MCH 500G OIGNON RO,food,,5.5,...,MCH 500G OIGNON RO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
24,2025-04-25,receipt,1,NaN,NaN,FILET AIL 3 TETES,FILET AIL 3 TETES,food,,5.5,...,FILET AIL 3 TETES,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
25,2025-04-25,receipt,1,NaN,NaN,FLT 350G ECHALOTE,FLT 350G ECHALOTE,food,,5.5,...,FLT 350G ECHALOTE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
26,2025-04-25,receipt,1,NaN,NaN,COURGETTE,COURGETTE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.146439
27,2025-04-25,receipt,1,NaN,NaN,8X125G LAUTHENTIQ,8X125G LAUTHENTIQ,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
28,2025-04-25,receipt,1,NaN,NaN,PAVE LE PAIN RUST,PAVE LE PAIN RUST,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
29,2025-04-25,receipt,1,NaN,NaN,FLT 2KG PDT CQLP,FLT 2KG PDT CQLP,food,,5.5,...,FLT 2KG PDT CQLP,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
30,2025-04-25,receipt,1,NaN,NaN,16X125 NATUR DANON,16X125 NATUR DANON,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
31,2025-04-25,receipt,1,NaN,NaN,320G JB SP DD SSOG,320G JB SP DD SSOG,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
32,2025-04-25,receipt,1,NaN,NaN,CELERI BRANCHE,CELERI BRANCHE,food,,5.5,...,CELERI BRANCHE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
33,2025-04-25,receipt,1,NaN,NaN,BANANE CRF BIO,BANANE CRF BIO,food,,5.5,...,BANANE CRF BIO,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
34,2025-04-25,receipt,1,NaN,NaN,POIVRON JAUNE,POIVRON JAUNE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.323326
35,2025-04-25,receipt,1,NaN,NaN,850G SKYR NATURE Y,850G SKYR NATURE Y,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
36,2025-04-25,receipt,1,NaN,NaN,125GX16 PAN0% PAN,125GX16 PAN0% PAN,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
37,2025-04-25,receipt,1,NaN,NaN,POMME GRANNY GROSS,POMME GRANNY GROSS,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.382772
38,2025-04-25,receipt,1,NaN,NaN,BRANDADE MORUE,BRANDADE MORUE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,8.89,NaN,NaN,1.360000
39,2025-04-25,receipt,1,NaN,NaN,BATAVIA PIECE,BATAVIA PIECE,food,,5.5,...,BATAVIA PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
40,2025-04-25,receipt,2,NaN,NaN,AVOCAT PIECE,AVOCAT PIECE,food,,5.5,...,AVOCAT PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
41,2025-04-25,receipt,1,NaN,NaN,MENTHE,MENTHE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.143539
42,2025-04-25,receipt,1,NaN,NaN,ORANGE DESSERT 2KG,ORANGE DESSERT 2KG,food,,5.5,...,ORANGE DESSERT 2KG,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
43,2025-04-25,receipt,1,NaN,NaN,PAIN CHOC PB X5 +,PAIN CHOC PB X5 +,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
44,2025-04-25,receipt,1,NaN,NaN,KIWI VERT PIECE,KIWI VERT PIECE,food,,5.5,...,KIWI VERT PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
45,2025-04-25,receipt,1,NaN,NaN,CHOU FLEUR PIECE,CHOU FLEUR PIECE,food,,5.5,...,CHOU FLEUR PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
46,2025-04-25,receipt,1,NaN,NaN,POIRE CONFERENCE,POIRE CONFERENCE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.236333
47,2025-04-25,receipt,1,NaN,NaN,CONCOMBRE PIECE,CONCOMBRE PIECE,food,,5.5,...,CONCOMBRE PIECE,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN
48,2025-04-25,receipt,1,NaN,NaN,CAROTTE VRAC,CAROTTE VRAC,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,9.38,NaN,NaN,NaN,0.127591
49,2025-04-25,receipt,1,NaN,NaN,1L HUILE FLEUR DE,1L HUILE FLEUR DE,food,,5.5,...,NaN,2025-04-25,0.0,1.36,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_prod[[f"totalPrice_{key}" for key in subcategories_matching.keys() if key in df_prod.columns]].sum(axis=1).head(30)

0      0.00
1      0.00
2      0.00
3      0.00
4      0.00
5     10.90
6      0.00
7      0.00
8     10.90
9      0.00
10     0.00
11     0.00
12     0.00
13    10.90
14     0.00
15     0.00
16    10.90
17     0.00
18     0.00
19     0.00
20     0.00
21    10.90
22     0.00
23     0.00
24     0.00
25     0.00
26     9.38
27     0.00
28     0.00
29     0.00
dtype: float64

In [ ]:
df_prod

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,date_loyalty_rayon,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred,totalTrueAmount
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,,5.5,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,,20.0,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,,5.5,...,2025-04-29,0.0,1.34,0.0,NaN,NaN,NaN,NaN,inf,-inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5020,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,,10.0,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.75
5021,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.50
5022,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.99
5023,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.61
5024,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,,5.5,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.18

In [ ]:
df_prod.fillna(
    {
        "amountRayonDeferred": 0,
        "itemRd": 0
    },
    inplace=True,
)

In [ ]:
df_prod['totalTrueAmount'] = df_prod['totalPriceAfterDiscount'] - df_prod['itemRd'] - df_prod['amountRayonDeferred']
df_prod[['dateKey', 'productLabel', 'totalPriceAfterDiscount', 'itemRd', 'amountRayonDeferred', 'totalTrueAmount']].head(30)

,dateKey,productLabel,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueAmount
0,2025-04-29,5X10 D FREEDENT ME,3.35,0.00,0.000000,3.350000
1,2025-04-29,KG POULET FERMIER,12.43,0.00,0.000000,12.430000
2,2025-04-29,750G OMEGA 3 DX SH,5.39,1.62,0.000000,3.770000
3,2025-04-29,3 RECH RUBAN MAGI,4.99,0.00,0.000000,4.990000
4,2025-04-29,132G BISC.COCO SSA,2.45,0.00,0.000000,2.450000
5,2025-04-29,KG TOMATE GRAP FR,5.86,0.00,0.720404,5.139596
6,2025-04-29,375G PIZZA BOLOGN.,4.14,0.00,0.000000,4.140000
7,2025-04-29,410G PIZZA 3 VIAND,4.72,0.00,0.000000,4.720000
8,2025-04-29,AUBERGINE VRAC,1.13,0.00,0.138917,0.991083
9,2025-04-29,20 OEUFS SOL,5.09,0.00,0.000000,5.090000
10,2025-04-29,400G COLIN FISH.CH,6.20,0.00,0.000000,6.200000
11,2025-04-29,BT 3X110MOUCH.CONF,12.41,0.00,0.000000,12.410000
12,2025-04-29,COCA-COLASSSCMINIC,3.65,0.00,0.000000,3.650000
13,2025-04-29,POIVRON ROUGE,0.69,0.00,0.084826,0.605174
14,2025-04-29,OY 1KG SPAGHETTI N,11.40,0.00,0.000000,11.400000
15,2025-04-29,12 RLX P.HYG.3P RO,7.80,0.00,0.000000,7.800000
16,2025-04-29,HARICOT VERT FIN,1.24,0.00,0.152440,1.087560
17,2025-04-29,132G SABLE CITRON,2.49,0.00,0.000000,2.490000
18,2025-04-29,200G LARDONS F +30,1.99,0.00,1.340000,0.650000
19,2025-04-29,150G GATEAU FOURRE,3.95,0.00,0.000000,3.950000
20,2025-04-29,BARRE MINCEUR CERE,8.99,0.00,0.000000,8.990000
21,2025-04-29,BQ TOM CERISE ALL,1.98,0.00,0.243413,1.736587
22,2025-04-25,MELON MOYEN,2.59,0.39,0.000000,2.200000
23,2025-04-25,MCH 500G OIGNON RO,2.99,0.45,0.000000,2.540000
24,2025-04-25,FILET AIL 3 TETES,3.19,0.47,0.000000,2.720000
25,2025-04-25,FLT 350G ECHALOTE,2.49,0.38,0.000000,2.110000
26,2025-04-25,COURGETTE,1.01,0.00,0.146439,0.863561
27,2025-04-25,8X125G LAUTHENTIQ,14.19,0.00,0.000000,14.190000
28,2025-04-25,PAVE LE PAIN RUST,2.05,0.00,0.000000,2.050000
29,2025-04-25,FLT 2KG PDT CQLP,3.07,0.46,0.000000,2.610000

In [ ]:
df_prod.loc[df_prod.totalWeight > 0, "totalTrueUnitPrice"] = (
    df_prod.loc[df_prod.totalWeight > 0, "totalTrueAmount"]
    / df_prod.loc[df_prod.totalWeight > 0, "totalWeight"]
)

In [ ]:
df_prod.query('productLabel.str.contains("saumon", case=False)')[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

,dateKey,productLabel,unitPrice,totalWeight,totalPrice,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueUnitPrice,totalTrueAmount
189,2025-03-29,FILET SAUMON FQC A,18.99,3.300,62.66,62.66,0.0,18.750000,13.306061,43.910000
249,2025-03-08,PAVE SAUMON,19.99,1.854,37.06,36.76,0.0,11.226210,13.772271,25.533790
557,2024-12-27,SAUMON ENTIER,8.90,2.913,25.93,25.93,0.0,0.000000,8.901476,25.930000
625,2024-12-15,420G PIZZA SAUMON,2.25,0.000,4.50,3.82,0.0,0.000000,NaN,3.820000
715,2024-11-19,TARTE SAUMON POIR.,3.89,0.000,7.78,5.45,0.0,0.000000,NaN,5.450000
728,2024-11-19,SAUMON ENTIER,9.99,1.998,19.96,19.96,0.0,2.256348,8.860687,17.703652
1022,2024-09-11,FILET SAUMON FQC A,11.99,5.268,63.17,63.17,0.0,6.508549,10.755780,56.661451
1867,2024-03-23,SAUMON ENTIER,11.99,4.904,58.80,58.80,0.0,0.000000,11.990212,58.800000
2555,2023-11-24,SAUMON ENTIER,9.99,2.808,28.05,28.05,0.0,0.000000,9.989316,28.050000
2833,2023-09-19,SAUMON ENTIER,9.99,2.430,24.28,24.28,0.0,0.000000,9.991770,24.280000
2874,2023-09-15,FILET SAUMON FQC A,12.99,2.218,28.81,28.81,0.0,0.000000,12.989179,28.810000
3055,2023-08-11,SAUMON ENTIER,9.99,5.700,56.94,56.94,0.0,0.000000,9.989474,56.940000
3069,2023-08-04,FILET SAUMON FQC A,13.99,2.310,32.32,32.32,0.0,0.000000,13.991342,32.320000
3986,2022-12-31,PAVE SAUMON,15.00,0.000,15.00,15.00,0.0,0.000000,NaN,15.000000
4758,2022-06-29,SAUMON SCE OSEILLE,4.95,0.000,4.95,4.95,0.0,0.000000,NaN,4.950000

In [ ]:
df_prod.query('productLabel.str.contains("H&S", case=False)')[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

Empty DataFrame
Columns: [dateKey, productLabel, unitPrice, totalWeight, totalPrice, totalPriceAfterDiscount, itemRd, amountRayonDeferred, totalTrueUnitPrice, totalTrueAmount]
Index: []

In [ ]:
df_prod.query('itemRd > 2')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,...,"ART RAYON BOUCHERIE TVA 5,5","ART RAYON FRUITS LEG TVA 5,5","ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON FRUITS LEG TVA 5,5","totalPrice_ART RAYON POISSONNERIE TVA 5,5","totalPrice_ART RAYON BOUCHERIE TVA 5,5","totalPrice_ART RAYON CHARCUTERIE TVA 5,5",amountRayonDeferred,totalTrueAmount,totalTrueUnitPrice
59,2025-04-17,receipt,1,NaN,NaN,396G SACH MEGA TO,396G SACH MEGA TO,food,,5.5,...,0.0,1.58,0.0,NaN,NaN,NaN,NaN,0.0,6.46,NaN
239,2025-03-15,receipt,2,NaN,NaN,RICORE RECHARGE 29,RICORE RECHARGE 29,food,,5.5,...,6.6,0.00,0.0,NaN,NaN,NaN,NaN,0.0,7.56,NaN
376,2025-02-01,receipt,1,NaN,NaN,70 COGNAC VS 40 HE,70 COGNAC VS 40 HE,other,,20.0,...,0.0,0.38,0.0,NaN,NaN,NaN,NaN,0.0,37.90,NaN
477,2025-01-14,receipt,1,NaN,NaN,FD ARIEL LIQ 3X22D,FD ARIEL LIQ 3X22D,other,,20.0,...,0.0,0.42,0.0,NaN,NaN,NaN,NaN,0.0,19.31,NaN
478,2025-01-14,receipt,1,NaN,NaN,FD ARIEL LIQ 3X22D,FD ARIEL LIQ 3X22D,other,,20.0,...,0.0,0.42,0.0,NaN,NaN,NaN,NaN,0.0,9.35,NaN
505,2025-01-05,order,1,8.700216e+12,7739158.0,Lessive Liquide Original ARIEL,lessive-liquide-original-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.32,NaN
508,2025-01-05,order,1,8.700216e+12,7746767.0,Lessive Liquide Ultra Détachant ARIEL,lessive-liquide-ultra-detachant-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.32,NaN
510,2025-01-05,order,1,8.700216e+12,7779560.0,Lessive Liquide Extra + Color Protection ARIEL,lessive-liquide-extra-color-protection-ariel,other,Lessives,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,33.28,NaN
545,2024-12-31,receipt,1,NaN,NaN,2X6TR 2X215G SF N,2X6TR 2X215G SF N,food,,5.5,...,2.9,0.00,0.0,NaN,NaN,NaN,NaN,0.0,15.39,NaN
847,2024-10-19,order,1,4.549651e+10,7749119.0,Jeu Pass Circuits additionnels Mario Kart 8 De...,jeu-pass-circuits-additionnels-mario-kart-8-de...,other,Nintendo Switch,NaN,...,0.0,1.10,0.0,NaN,NaN,NaN,NaN,0.0,19.49,NaN
899,2024-10-06,receipt,2,NaN,NaN,KALANCHOE COUPE DE,KALANCHOE COUPE DE,other,,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,15.98,NaN
1067,2024-09-06,receipt,2,NaN,NaN,2X75ML DENT S.G CA,2X75ML DENT S.G CA,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.25,NaN
1075,2024-09-06,receipt,2,NaN,NaN,2X75ML PSA GENC.EM,2X75ML PSA GENC.EM,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.26,NaN
1104,2024-09-06,receipt,2,NaN,NaN,2X75ML DENT PSA NE,2X75ML DENT PSA NE,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.10,NaN
1498,2024-06-15,receipt,3,NaN,NaN,3X75ML DENT WN TP,3X75ML DENT WN TP,other,,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.91,NaN
1602,2024-05-24,receipt,1,NaN,NaN,3X150G LT3 DELIC L,3X150G LT3 DELIC L,food,,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.36,NaN

In [ ]:
df_prod.query('productLabel.str.contains("Citrus", case=False)')

Empty DataFrame
Columns: [dateKey, recordType, countVisits, ean, cdbase, productLabel, slugProductLabel, category, subCategory_original, vatPercentage, totalQuantity, totalWeight, unitPrice, totalPrice, totalImmediateDiscount, totalPriceAfterDiscount, subCategory_imputed, date, itemLabel, itemRd, matchedLabel, date_loyalty_rayon, ART RAYON BOUCHERIE TVA 5,5, ART RAYON FRUITS LEG TVA 5,5, ART RAYON POISSONNERIE TVA 5,5, totalPrice_ART RAYON FRUITS LEG TVA 5,5, totalPrice_ART RAYON POISSONNERIE TVA 5,5, totalPrice_ART RAYON BOUCHERIE TVA 5,5, totalPrice_ART RAYON CHARCUTERIE TVA 5,5, amountRayonDeferred, totalTrueAmount, totalTrueUnitPrice]
Index: []

[0 rows x 32 columns]

In [ ]:
df_loyalty.query("date == @pd.to_datetime('2024-05-09')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
219,63092555004,2024-05-09,0.0,-20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_loyalty.query('itemLabel.notna() & itemLabel.str.contains("Citrus", case=False)')

Empty DataFrame
Columns: [operationId, date, earned, burned, itemLabel, promotionLabel, itemRd, loyaltyOperation, embeddingLabel, matchedLabel1, similarity_score1, matchedLabelFuzzy, matchedLabel2, similarity_score2, matchedLabel]
Index: []

In [ ]:
df_loyalty.itemLabel.unique()

array(['20 OEUFS DJP POULE AU SOL CRF', 'BANANE CRF BIO MH 5 FRUITS',
       '1KG COUSCOUS MOYEN CRF', nan, 'FLT 500G CITRON VERT',
       '1KG FROMAGE FRAIS 0%MG CRF CLA', 'OIGNON ROUGE BOTTE',
       'PAIN COMPLET CRF BIO 400G', 'ART RAYON FRUITS LEG TVA 5,5',
       'ST 200G HARICOT.MUNGO 0,99', 'ARTICHAUT PIECE',
       'FLT ECHALOTE 500G SIMPL FR', 'FILET AIL 3 TETES',
       '16X125G YRT FRUIT 0% CRF CLASS', 'RADIS ROSE BOTTE',
       'FLT 350G ECHALOTE FR', 'ART RAYON POISSONNERIE TVA 5,5',
       '125G MOZZARELLA VACHE', '16X125G BIF NATURE ACTIVIA OD',
       '2X75ML DENT PSA NETT INTENS OB', '2X75ML PSA GENC&EMAIL ORIG OB',
       'AG SCOL OXFORD FLOWERS 12X18', '2X75ML DENT S&G CALM ORIGIN OB',
       '500G LUTTI HAPPY FIZZ', 'SWITCH SET MARIO KART 8 PASS C',
       'FLT 1,5KG ORANGE DESSERT CRF', 'BQ 200G CHAMPIGNONS BRUN FQC',
       'BROCOLI PCE FR', 'KIWI VERT PIECE', 'BATAVIA SALADE PIECE',
       'BQ250G TT CERISE ALL SIMPL HF', 'CITRON VERT PIECE',
       'AVOCAT PIECE', 'KALANCHOE COUPE DE 23',
       '1L BOISSON SOJA NATUR CARF BIO', 'POMELO PIECE',
       'ST 1,5KG POMME GALA FR', 'RUBAN TRANSPT 550 19MMX33M',
       'MAIS SANS SUCRE AJOUTE BOITE 3', '3X1/4 MAIS SS AJOUTE CRF CLASS',
       'ART RAYON BOUCHERIE TVA 5,5', '2X6TR 2X215G SF NOR',
       'FLT 2KG ORANGE DESSERT CRF HF', 'KAKI PIECE',
       'POTIMARRON PIECE FR', '750G OMEGA 3 DX ST HUBERT',
       'MELON MOYEN PIECE', 'CHOU FLEUR  PIECE',
       'MCH 500G OIGNON ROUGE FQC FR', 'FLT 350G ECHALOTE FQC FR',
       'MENTHE FRAICHE BOTTE', 'FLT 2KG PDT VP BL CQLP FR',
       'BATAVIA PIECE', 'CONCOMBRE PIECE', 'BASILIC FRAIS BOTTE',
       "396G SACH MEGA T'OEUF PETIL", 'PERSIL PLAT FRAIS BOTTE MAX',
       'FLT 6 BULBES OIGNON JN FR', 'ST 400G EPINARD FR',
       'CHOU ROUGE PIECE', '1KG FILET POULET PLK', 'KIWI VERT FQC PIECE',
       'FLT2KG PDT CONS FPP CRF FR', '300G BISCOT.GERM.BLE BIO CRF',
       '1L BOISSON RIZ NOISET CRF BIO', 'ACETONE 1L',
       'BQ400G TOM CERISE ALL IMP', 'PQ 1KG FARINE TYPE 65 CRF BIO',
       'FLT2KG PDT CONS FPP FQC', 'ARIEL LIQ 3X22D ACTIVE',
       'LTX3 ARIEL LIQ 22D UNSTOPPABLE', 'ARIEL LIQUIDE 34D ORIGINAL',
       'ARIEL LIQUIDE 31D PROTECTION', 'ARIEL LIQUIDE 31D ULTRA',
       '1X8L FF BP MATIN LEGER ECREME', 'PCE CHOU BROCOLIS CRF CEE',
       'ST 500G BETTERAVE FQC AGR', 'BANANE 5 DOIGTS 0.99 HF',
       '1KG FARINE BLE T45 CRF CLASSIC', '1KG FARINE BLE FLUID T45 CRF C',
       '3X75ML DENT WN TP SENS SIGNAL', '4X138G CROUSTILLE EMTL. BELIN',
       'PDA PAVE CRF BIO 500G', 'FLT 2KG ORANGE DESSERT FQC HF',
       'FLT 2KG PDT BLC VAP FQC FR', 'ST 2PCES MAIS DOUX HF',
       'PAIC BI ACTIV SEL MINERAL2X750', '12X125G YAOURTS PAT LA LAIT',
       'FLT 2KG PDT FRITE FQC FR', '70CL COGNAC VS 40% HENNESSY',
       'ST 500G BETTERAV PRIM FQC AGRO', 'MANCH. 500G OIGNON ROUGE FR',
       'FLT 1 KG PDT CONSO 0.99 SIMPL', '20X OEUFS DJP SOL CRF  CLASSIC',
       'SALADE BATAVIA PIECE', '400 ML LT CORPS NUTRI ARG LPM',
       '550G PAIN SANDW.CEREAL CRF CLA', 'CORIANDRE FRAIS BOTTE',
       '125G MOZZARELLA BUFALA BIO CRF', 'FLT 2KG PDT BLC VAP CRF FR',
       '100G GRANA PADANO RAPE AOP CRF', 'MELON PETIT PIECE',
       'RICORE RECHARGE 290G'], dtype=object)

In [ ]:
df_loyalty.query("date == @pd.to_datetime('2024-05-09')")

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
219,63092555004,2024-05-09,0.0,-20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_prod.query("dateKey == @pd.to_datetime('2024-05-09')")[
    ["dateKey", "productLabel", "unitPrice", "totalWeight", "totalPrice", "totalPriceAfterDiscount", "itemRd", "amountRayonDeferred", "totalTrueUnitPrice", "totalTrueAmount"]
]

,dateKey,productLabel,unitPrice,totalWeight,totalPrice,totalPriceAfterDiscount,itemRd,amountRayonDeferred,totalTrueUnitPrice,totalTrueAmount
1653,2024-05-09,KIWI VERT PIECE,0.59,0.000,2.36,2.00,0.0,0.0,NaN,2.00
1654,2024-05-09,750G CASSONADE,2.69,0.000,2.69,2.69,0.0,0.0,NaN,2.69
1655,2024-05-09,BT 3X110MOUCH.CONF,3.89,0.000,7.78,7.78,0.0,0.0,NaN,7.78
1656,2024-05-09,24 PS EXTRA LONG C,1.55,0.000,1.55,1.55,0.0,0.0,NaN,1.55
1657,2024-05-09,POIVRON ROUGE,3.99,0.514,2.05,2.05,0.0,0.0,3.988327,2.05
1658,2024-05-09,OUTILS 13-1 BOSCH,17.99,0.000,17.99,3.00,0.0,0.0,NaN,3.00
1659,2024-05-09,AVOCAT PIECE,1.19,0.000,2.38,1.80,0.0,0.0,NaN,1.80
1660,2024-05-09,KG POMME FUJI FQC,1.99,1.151,2.29,2.29,0.0,0.0,1.989574,2.29
1661,2024-05-09,226G PICANTE SALSA,2.99,0.000,5.98,4.18,0.0,0.0,NaN,4.18
1662,2024-05-09,SOURIS TIPP EX X2,3.79,0.000,3.79,3.79,0.0,0.0,NaN,3.79
1663,2024-05-09,PRESIDENT LE BLEU,3.39,0.000,3.39,3.39,0.0,0.0,NaN,3.39
1664,2024-05-09,6X1.5L CRISTALINE,1.14,0.000,1.14,1.14,0.0,0.0,NaN,1.14
1665,2024-05-09,KNACKI ORIGINAL PO,1.99,0.000,1.99,1.99,0.0,0.0,NaN,1.99
1666,2024-05-09,NESCAFE SPEC.FILTR,6.89,0.000,13.78,12.28,0.0,0.0,NaN,12.28
1667,2024-05-09,SH 2EN1 CLASSIC 62,11.09,0.000,11.09,11.09,0.0,0.0,NaN,11.09
1668,2024-05-09,FEUTRE POINT 88 AS,2.65,0.000,2.65,2.65,0.0,0.0,NaN,2.65
1669,2024-05-09,COURGETTE,2.49,0.799,1.99,1.99,0.0,0.0,2.490613,1.99
1670,2024-05-09,10 PORTIONS TARTAR,2.19,0.000,2.19,2.19,0.0,0.0,NaN,2.19
1671,2024-05-09,TORTI CHIPS PAPRIK,3.55,0.000,7.10,4.98,0.0,0.0,NaN,4.98
1672,2024-05-09,5X10 D FREEDENT WH,2.35,0.000,4.70,3.52,0.0,0.0,NaN,3.52
1673,2024-05-09,2X75G EMINCES DE P,2.99,0.000,2.99,2.99,0.0,0.0,NaN,2.99
1674,2024-05-09,KG TOMATE GRAP FR,2.49,0.434,1.08,1.08,0.0,0.0,2.488479,1.08
1675,2024-05-09,305G RAVIOLI 4 FRO,2.69,0.000,2.69,2.69,0.0,0.0,NaN,2.69
1676,2024-05-09,ORANGE DESSERT 2KG,3.19,0.000,3.19,3.19,0.0,0.0,NaN,3.19
1677,2024-05-09,MENTHE,0.99,0.000,0.99,0.99,0.0,0.0,NaN,0.99
1678,2024-05-09,6T F BLC PLT DORE,2.19,0.000,2.19,2.19,0.0,0.0,NaN,2.19
1679,2024-05-09,POIRE CONFERENCE,3.49,0.888,3.10,3.10,0.0,0.0,3.490991,3.10